// GENEROVÁNO z obsah/hlasky.md — needitovat ručně.
// Přegenerování: node nastroje/generuj-hlasky.mjs
//
// Použití:  import { h } from './hlasky.js';
//           el('p', { text: h('zamceno.faze', { datum: '1. 11.' }) })
// Výstup h() je PROSTÝ TEXT — vkládej přes textContent / el({text}), nikdy jako HTML.
// Čisté funkce bez DOM, importovatelné i v Node.

/** Všechny hlášky: klíč 'skupina.nazev' → text s proměnnými {nazev}. */
export const HLASKY = Object.freeze({
  "zak.spravne": "Správně!",
  "zak.zkus_znovu": "Ještě to nesedí. Zkus to znovu, máš ještě jeden pokus.",
  "zak.nesedi_dal": "Zatím to nesedí. Nevadí, jdeme dál. Rodič má u sebe otázky, které pomůžou.",
  "zak.spravne_zkrat": "Výsledek je správně, ale uprav ho do základního tvaru.",
  "zak.uloha_hotova": "Úloha {n} ze 4 je hotová. Pokračuj další.",
  "zak.tip_zvyrazneni": "Tip: klikni na číslo nebo slovo v zadání a podtrhne se.",
  "zak.konec": "Hotovo, dnešní lekce je za tebou! Zavolej rodiče, na telefonu teď dokončí semafor.",
  "zak.konec_nadpis": "Hotovo, ukaž telefon rodiči",
  "zak.posledni_uloha_hotova": "Poslední úloha je hotová.",
  "zak.napoveda_zvyrazneni": "Klikni na slovo nebo číslo a podtrhni si ho.",
  "zak.zadani_pokracuje": "Zadání pokračuje",
  "zak.neplatne_dlazdice": "Nejdřív vyber jednu možnost.",
  "zak.neplatne_cislo": "Zapiš výsledek číslem, třeba 12 nebo 2,5.",
  "zak.neplatne_zlomek": "Vyplň čitatel i jmenovatel celými čísly. Jmenovatel nesmí být 0.",
  "zak.neplatne_smisene": "Vyplň celou část, čitatel i jmenovatel celými čísly.",
  "zak.neplatne_text": "Napiš svou odpověď.",
  "zak.neplatne_vyraz": "Zapiš výraz, třeba 3x − 2 nebo 2(x + 1). Krát piš · nebo *, mocninu x².",
  "zak.neplatne_poradi": "Klikni postupně na všechny početní operace, pak odevzdej.",
  "zak.vyraz_zjednodus": "Hodnota sedí, ale výraz ještě zjednoduš.",
  "zak.vyraz_roznasob": "Hodnota sedí, ale ještě roznásob závorku.",
  "zak.vyraz_soucin": "Hodnota sedí, ale výsledek má být součin. Zkus výraz rozložit.",
  "zak.vyraz_nahled": "Takhle to čtu:",
  "zak.vyraz_nahled_nejde": "zatím to nedokážu přečíst",
  "zak.poradi_napoveda": "Klikni na znaménka v tom pořadí, v jakém počítáš. Dalším klikem číslo zrušíš.",
  "zak.poradi_znovu": "Začít znovu",
  "zak.opakovana_odpoved": "Tahle odpověď už byla. Zkus jinou.",
  "zak.odevzdano_text": "Odevzdáno. Tohle si projdete s rodičem.",
  "zak.papir_nadpis": "Počítáš na papír, výsledky zadá rodič",
  "zak.papir_text": "Úlohy máš vytištěné. Až budeš mít hotovo, ukaž papír rodiči. Výsledky zapíše do telefonu.",
  "zak.pripravit_nadpis": "Připrav si",
  "zak.pripravit_text": "Než začneš, dej si na stůl všechno, co budeš potřebovat. Co máš, odškrtni.",
  "zak.pripravit_tlacitko": "Mám připraveno, jdu na to",
  "zak.pripravit_zbyva": "Odškrtni všechno, pak můžeš začít.",
  "rodic.tri_pravidla": "Tři pravidla: 1) Nepočítáte a nepíšete, jen se ptáte. 2) Dítě vysvětluje vám, ne vy jemu. 3) Po každé úloze klikněte do semaforu, co jste viděli.",
  "rodic.stav_nic": "Dítě zatím nic neodevzdalo.",
  "rodic.stav_spravne": "Dítě odevzdalo: {krok} ✔",
  "rodic.stav_nesedi": "Dítě odevzdalo: {krok}, zatím nesedí. Zkuste otázky níže.",
  "rodic.stav_nesedi_kontrolni": "Dítě odevzdalo: {krok}, zatím nesedí. Podívejte se do typické chyby.",
  "rodic.stav_obnovit": "Obnovit stav",
  "rodic.stav_naposledy": "Naposledy načteno v {cas}.",
  "rodic.papir_vysledek": "Opište výsledek, který dítě napsalo na papír. Nic nepočítejte.",
  "rodic.dalsi_otazka": "Další otázka",
  "rodic.ukazat_reseni": "Ukázat řešení",
  "rodic.semafor_nadpis": "Co jste viděli?",
  "rodic.volba_sam": "Vyřešil(a) sám/sama",
  "rodic.volba_s_otazkou": "Potřeboval(a) otázku",
  "rodic.volba_chyba_pocty": "Spletl(a) se",
  "rodic.klic_uvod": "Klikněte podle toho nejtěžšího, co se stalo: Nevěděl(a) > Spletl(a) se > Potřeboval(a) otázku > Sám/sama.",
  "rodic.klic_tlacitko": "Jak vybrat?",
  "rodic.klic_sam": "Došlo k cíli samo, bez vaší otázky.",
  "rodic.klic_s_otazkou": "Došlo k cíli po některé z otázek. Patří sem i: spletlo se, ale po otázce se opravilo.",
  "rodic.klic_chyba_pocty": "Postup znalo, ale výpočet nedotáhlo nebo se spletlo (v čísle, znaménku, pravidle, výběru) a neopravilo to.",
  "rodic.klic_nevedel": "Ani po třetí otázce se nepohnulo, po otázce jen tipovalo dlaždice, nebo většinu úlohy nezvládlo.",
  "rodic.otocena_odpoved": "Jak zní dobrá odpověď?",
  "rodic.co_vidi_dite": "Co vidí dítě",
  "rodic.cteni_zapisu": "Jak číst zápisy nahlas",
  "rodic.zitra_zelena": "Zítra: nová lekce.",
  "rodic.zitra_oranzova": "Zítra: nejdřív 5minutové cvičení z doporučení níže, pak nová lekce. Je-li cvičení víc, stačí to u poslední úlohy.",
  "rodic.zitra_cervena": "Dnes skončete a pochvalte snahu. Zítra místo nové lekce: cvičení z doporučení níže, pak znovu tato lekce.",
  "rodic.volba_nevedel": "Nevěděl(a), jak začít",
  "rodic.uvod_nadpis": "Než začnete",
  "rodic.plati": "Platí:",
  "rodic.pravidla_nadpis": "Pravidla pro vás",
  "rodic.pravidla_1": "Nic nepočítáte ani nepíšete.",
  "rodic.pravidla_2": "Ptáte se otázkami z taháku. Nic nevysvětlujete.",
  "rodic.pravidla_3": "Chválíte snahu a postup, ne výsledek.",
  "rodic.postup_1": "Dítě čte a řeší. Vy mlčíte.",
  "rodic.postup_1_kontrolni": "Dítě řeší samo, vy jen sledujete.",
  "rodic.postup_2": "Zasekne se? Přečtěte otázku.",
  "rodic.postup_2_pozn": "Další otázku čtěte, až když předchozí nepomůže.",
  "rodic.postup_2_pozn_priklady": "Každý příklad má svou otázku. Čtěte ji u příkladu, kde se dítě zasekne.",
  "rodic.postup_3": "Hotovo? Zeptejte se:",
  "rodic.postup_4": "Klikněte, jak to šlo",
  "rodic.pro_jistotu": "Pro jistotu",
  "rodic.krok_hotovo": "Hotovo",
  "rodic.nezaseklo": "Nezaseklo se",
  "rodic.krok_hotovo_stav": "hotovo",
  "rodic.chybi_krok": "Nejdřív odškrtněte krok {n}.",
  "rodic.chybi_semafor": "Nejdřív klikněte, jak to šlo.",
  "rodic.pouzili_otazku": "Použili jste otázku",
  "rodic.barva_zelena": "Zelená: zvládnuto",
  "rodic.barva_oranzova": "Oranžová: zítra 5 minut procvičit",
  "rodic.barva_cervena": "Červená: dnes stačí, zítra znovu",
  "rodic.zelena_s_otazkou": "Příště zkuste podobnou úlohu bez otázky.",
  "rodic.zmenit_volbu": "Volbu můžete změnit.",
  "rodic.konec": "Lekce je hotová. Pochvalte dítě za práci, ne za výsledek. Doporučení na zítra najdete níže.",
  "rodic.konec_tlacitko": "Ukončit lekci",
  "rodic.sos_nabidka": "Tohle téma dnes znovu nešlo. Nechcete ho probrat s lektorem? Online konzultace 30 minut, 150 Kč.",
  "rodic.sos_nadpis": "Druhá červená v řadě u tématu {kapitola_nazev}",
  "rodic.vsechny_otazky": "To jsou všechny otázky",
  "rodic.papir_nadpis": "Výsledek dítěte (papír)",
  "rodic.vyraz_zjednodus": "Hodnota sedí, ale výraz není dokončený: dá se ještě zjednodušit. Počítá se jako nesprávně.",
  "rodic.vyraz_roznasob": "Hodnota sedí, ale výraz není dokončený: závorka se má roznásobit. Počítá se jako nesprávně.",
  "rodic.vyraz_soucin": "Hodnota sedí, ale výsledek má být součin (vytknutý nebo rozložený podle vzorce). Počítá se jako nesprávně.",
  "rodic.papir_neplatne": "Zkontrolujte prosím zadaný výsledek.",
  "rodic.poradi_papir_nadpis": "Pořadí operací (papír)",
  "rodic.poradi_papir_text": "Takhle je to správně. Porovnejte s čísly na papíře dítěte.",
  "rodic.poradi_papir_vice": "Správně je kterékoli z těchto pořadí. Porovnejte s čísly na papíře dítěte.",
  "rodic.poradi_sedi": "Sedí",
  "rodic.poradi_nesedi": "Nesedí",
  "rodic.poradi_dite": "Dítě klikalo:",
  "rodic.poradi_chyba": "Typická chyba:",
  "rodic.poradi_spravne": "Správně:",
  "rodic.poradi_spravne_i": "Správně je i:",
  "rodic.obrazek_popis": "Na obrázku: {popis}",
  "rodic.ukazat_kontrolu": "Ukázat kontrolu",
  "rodic.posledni_uloha": "Poslední úloha",
  "rodic.souhrn_nadpis": "Souhrn lekce",
  "rodic.souhrn_hlavni": "Hlavní barva lekce",
  "rodic.souhrn_na_zitra": "Na zítra",
  "rodic.souhrn_upravit": "Upravit semafor",
  "rodic.souhrn_jen_cteni": "Lekce je dokončená ({datum}). Souhrn je jen pro čtení.",
  "rodic.lekce_ukoncena": "Lekce je uložená. Pochvalte dítě a zítra pokračujte.",
  "oba.cas_vyprsel": "Doporučený čas vypršel. Můžete dokončit nebo zavřít.",
  "oba.max_lekce_den": "Dnešní lekce je hotová. Další doporučujeme až zítra.",
  "oba.pripravit_tisk": "Připrav si: {pomucky}",
  "oba.tisk_zpet_lekce": "Zpět k lekci",
  "oba.tisk_zpet_prehled": "Zpět na přehled",
  "oba.tisk_odkaz": "Úlohy k tisku",
  "oba.poradi_tisk": "Očísluj, v jakém pořadí počítáš.",
  "zamceno.faze": "Otevře se {datum}.",
  "ucet.uzavreny_nadpis": "Děkujeme, že jste opakovali s námi",
  "ucet.uzavreny": "Účet je uzavřený a lekce už nejsou dostupné. Držíme palce v osmé třídě i dál!",
  "ucet.uzavreny_doucovani": "Chcete pokračovat v doučování? Napište nám na {email} nebo se podívejte na studentbase.cz.",
  "ucet.chyba_jmeno": "Napište prosím své jméno.",
  "ucet.chyba_email_prazdny": "Napište prosím e-mail.",
  "ucet.chyba_email_tvar": "Zkontrolujte prosím e-mail, chybí v něm zavináč, tečka nebo koncovka (např. .cz).",
  "ucet.chyba_email_kratce": "Zkontrolujte prosím e-mail.",
  "ucet.chyba_heslo_kratke": "Heslo musí mít alespoň 8 znaků.",
  "ucet.chyba_heslo_kratke_pocet": "Heslo musí mít alespoň 8 znaků (teď má {n}).",
  "ucet.chyba_heslo_prazdne": "Napište prosím heslo.",
  "ucet.chyba_hesla_neshoda": "Hesla se neshodují. Napište prosím dvakrát stejné heslo.",
  "ucet.chyba_dite": "Napište prosím křestní jméno dítěte.",
  "ucet.chyba_skola": "Vyberte prosím typ školy.",
  "ucet.chyba_znamka": "Vyberte prosím známku. Když si nejste jistí, zvolte tu nejbližší.",
  "ucet.chyba_souhlas": "Pro registraci je potřeba souhlas s podmínkami.",
  "ucet.nenacteno": "Nepodařilo se spojit se serverem. Zkontrolujte připojení a obnovte stránku.",
  "ucet.obnova_odeslano_nadpis": "Poslali jsme vám odkaz",
  "ucet.obnova_odeslano": "Pokud je adresa {email} u nás registrovaná, přijde na ni za chvíli e-mail s odkazem na nové heslo. Nic nepřišlo? Podívejte se do složky Hromadné nebo Spam.",
  "ucet.odkaz_neplatny": "Odkaz pro nové heslo je neplatný nebo vypršel. Požádejte prosím o nový.",
  "ucet.nove_heslo_ulozeno": "Heslo je změněné. Přesměrováváme vás na přehled…",
  "chyba.ulozeni": "Nepodařilo se uložit, zkuste obnovit stránku. Odpovědi zatím držíme a zkusíme je uložit znovu.",
  "chyba.ulozeni_ok": "Uloženo.",
  "chyba.nacteni": "Nepodařilo se načíst data. Zkontrolujte připojení a obnovte stránku.",
  "chyba.offline": "Jste offline. Jakmile se připojení vrátí, vše uložíme.",
  "chyba.tisk_nenacteno": "Tiskovou verzi se nepodařilo načíst. Zkontrolujte připojení a obnovte stránku.",
  "chyba.tisk": "Tisk se nepodařilo spustit. Zkuste v menu prohlížeče Sdílet → Tisk.",
  "prazdny.lekce": "Zatím tu nejsou žádné lekce. Brzy je doplníme.",
  "prazdny.deti": "Zatím tu není žádné dítě. Přidejte ho, ať může začít.",
  "prazdny.souhrn": "Tady se ukáže souhrn po první dokončené lekci.",
  "obnoveni.rodic": "Máte rozpracovanou lekci {tema} (úloha {n} z {celkem}). Chcete pokračovat, kde jste skončili?",
  "obnoveni.pokracovat": "Pokračovat",
  "obnoveni.znovu": "Začít znovu",
  "obnoveni.zak": "Vítej zpátky! Pokračuješ úlohou {n}.",
  "sos.nadpis": "Potřebujete pomoc?",
  "sos.text": "Když se téma opakovaně nedaří, probereme ho spolu. Online konzultace s lektorem StudentBase: 30 minut, 150 Kč, platí se zvlášť. Napište nám a ozveme se s termínem.",
  "sos.tlacitko": "Napsat e-mail",
  "sos.mailto_predmet": "SOS: {kapitola_nazev} — {jmeno_ditete}",
  "sos.mailto_telo": "Dobrý den,\n\npotřebujeme pomoc s tématem {kapitola_nazev}.\n\nDítě: {jmeno_ditete}\nLekce: {lekce_tema} ({lekce_id})\nCo nešlo: \n\nKdy se nám hodí konzultace (dny a časy): \n\nDěkuji,\n{jmeno_rodice}",
  "dite.pridat_tlacitko": "Přidat druhé dítě",
  "dite.pridat_nadpis": "Přidat druhé dítě",
  "dite.pridat_text": "Druhé dítě je zdarma a má vlastní průběh lekcí.",
  "dite.prvni_nadpis": "Přidejte profil dítěte",
  "dite.prvni_tlacitko": "Přidat profil dítěte",
  "dite.ulozit": "Uložit profil",
  "dite.pridano": "Profil dítěte {jmeno} je přidaný.",
  "dite.max_2": "Můžete mít nejvýše 2 profily dětí.",
  "diag.karta_podtitul": "Asi 20 krátkých úloh, asi 25 minut. Ukáže, kterým tématům dát víc času.",
  "diag.karta_doporuceni": "Doporučujeme udělat ji před týdnem 1.",
  "diag.karta_sekce": "Týden 0 — vstupní diagnostika",
  "diag.karta_zacit": "Začít diagnostiku",
  "diag.karta_zacit_zak": "Začít",
  "diag.karta_hotovo": "Hotovo",
  "diag.karta_vysledek": "Výsledek diagnostiky",
  "diag.start_rodic": "Dítě pracuje samo, vy nenapovídáte. Po polovině si může dát přestávku.",
  "diag.prubeh": "Úloha {n} {z} {celkem}",
  "diag.ulozeno": "Uloženo.",
  "diag.prestavka_nadpis": "Máš za sebou polovinu.",
  "diag.prestavka_text": "Dej si pět minut pauzu. Napij se, protáhni se. Pak dokončíš druhou polovinu.",
  "diag.prestavka_pokracovat": "Pokračovat",
  "diag.prestavka_jindy": "Dokončím jindy",
  "diag.konec_nadpis": "Hotovo. Díky!",
  "diag.konec_text": "Výsledek uvidí rodič na telefonu. Ty už nic dalšího dělat nemusíš.",
  "diag.rodic_uvod": "Dítě teď pracuje samo. Vy nenapovídáte, nekontrolujete a nekoukáte přes rameno.",
  "diag.rodic_odevzdano": "Odevzdáno {x} {z} {celkem}",
  "diag.rodic_polovina_1": "1. polovina",
  "diag.rodic_polovina_2": "2. polovina",
  "diag.rodic_uplynulo": "Uplynulo {min} min",
  "diag.rodic_cas": "Uplynulo přes půl hodiny. Pokud dítě ještě pracuje a nemá toho dost, nechte ho dokončit. Pokud je unavené, domluvte se na pokračování jindy.",
  "diag.rodic_rady_nadpis": "Co dělat, když…",
  "diag.rodic_rada_1": "Dítě se ptá, jestli to má dobře: „To se dozvíme na konci. Teď jdi dál.“",
  "diag.rodic_rada_2": "Dítě nerozumí slovu v zadání: slovo můžete vysvětlit, příklad ne.",
  "diag.rodic_rada_3": "Po polovině aplikace dítěti nabídne přestávku. Nechte ho vybrat.",
  "diag.rodic_zobrazit": "Zobrazit výsledek",
  "diag.rodic_ukoncit_potvrzeni": "Dítě odevzdalo {x} {z} {celkem} úloh. Když teď výsledek zobrazíte, diagnostika se uzavře a zbylé úlohy už dítě neudělá. Pokračovat?",
  "diag.rodic_orientacni": "Výsledek bude jen orientační.",
  "diag.rodic_zpet": "Zpět",
  "diag.rodic_ano": "Ano, zobrazit",
  "diag.papir_uvod": "Až dítě dopíše, přepište sem jeho výsledky.",
  "diag.papir_prepsat": "Přepsat výsledky",
  "diag.papir_pokyn": "Přepište přesně to, co dítě napsalo. Nic neopravujte. Prázdnou úlohu nechte prázdnou.",
  "diag.papir_ulozit": "Uložit výsledky",
  "diag.papir_blok_1": "1. polovina",
  "diag.papir_blok_2": "2. polovina",
  "diag.tisk_prestavka": "Polovina. Dej si pět minut pauzu.",
  "diag.zadna": "Diagnostiku zatím nemáte hotovou.",
  "diag.nesestaveno": "Výsledek se nepodařilo sestavit. Zkuste obnovit stránku.",
  "diag.vysledek_nadpis": "Výsledek vstupní diagnostiky",
  "diag.vysledek_podnadpis": "{jmeno_ditete}, {datum}",
  "diag.jak_nalozit_nadpis": "Jak s výsledkem naložit",
  "diag.jak_nalozit_1": "Výsledek je pro vás, ne pro dítě. Neříkejte mu počty ani „tohle neumíš“. Stačí: „Díky, teď víme, čím začít.“",
  "diag.jak_nalozit_2": "Diagnostika ukazuje, kde začít, ne co dítě umí napořád. Za pár týdnů to bude jinak.",
  "diag.jak_nalozit_3": "Začněte týdnem 1, i když vyšel jistě. Týdny na sebe navazují.",
  "diag.plan_nadpis": "Plán Fáze 1 po týdnech",
  "diag.kapitoly_nadpis": "Jak si dítě vedlo v kapitolách",
  "diag.chyby_nadpis": "Na co dítě nejčastěji naráží",
  "diag.chyby_trenuje": "Trénuje se v týdnu {tydny}.",
  "diag.chyby_vickrat": "Objevilo se víckrát.",
  "diag.chyby_prazdne_prehlednuti": "Chyby, které se objevily, nepatří k těm typickým. Vypadají spíš jako přehlédnutí.",
  "diag.chyby_prazdne": "V úlohách, které dítě odevzdalo, se žádná typická chyba neobjevila.",
  "diag.stav_jista": "Jisté",
  "diag.stav_nejista": "Nejisté",
  "diag.stav_slaba": "Potřebuje víc času",
  "diag.stav_nezjisteno": "Nevíme",
  "diag.kapitola_jista": "Úlohy z této kapitoly dítě vyřešilo.",
  "diag.kapitola_nejista": "Něco vyšlo, něco ještě ne.",
  "diag.kapitola_slaba": "Tady dítě zatím chybuje. Tomuhle týdnu dejte čas.",
  "diag.kapitola_nezjisteno": "Na tyto úlohy dítě nedošlo.",
  "diag.kapitola_jedna_uloha": "Jen jedna úloha, berte orientačně.",
  "diag.kapitola_tyden": "Týden {tyden}",
  "diag.duraz_dukladne": "Projděte důkladně",
  "diag.duraz_normalne": "Běžné tempo",
  "diag.duraz_rychleji": "Může jít rychleji",
  "diag.duraz_nezjisteno": "Nevíme",
  "diag.duraz_opakovani": "Opakování",
  "diag.tyden_dukladne": "Všechny 4 lekce, jedna denně. Když lekce skončí oranžovou, zopakujte ji další den.",
  "diag.tyden_normalne": "Jedna lekce denně podle plánu.",
  "diag.tyden_rychleji": "Když lekce vycházejí zeleně, nemusíte čekat na další týden a můžete pokračovat hned.",
  "diag.tyden_nezjisteno": "Na tyto úlohy dítě v diagnostice nedošlo. Projděte týden běžným tempem.",
  "diag.tyden_opakovani": "Projděte ho vždycky, vrací se v něm látka ze všech týdnů.",
  "diag.tyden_nazev": "Týden {tyden} · {nazev}",
  "diag.tyden_lekce_duraz": "Nejvíc času dejte lekcím {lekce}.",
  "diag.tyden_pilot": "Než týden začnete, vraťte se k pilotní lekci {pilot}. Je pořád otevřená.",
  "diag.celkem_pevne": "Základy z 6. až 8. třídy jsou pevné. Ve Fázi 1 půjde hlavně o jistotu a pečlivý zápis.",
  "diag.celkem_vetsinou": "Základy dítě většinou má. Víc času dejte týdnům, které jsou níže označené „Projděte důkladně“.",
  "diag.celkem_cast": "Část základů zatím chybí. Fáze 1 je přesně na to: jděte týden po týdnu a nic nepřeskakujte.",
  "diag.celkem_zacatek": "Základy jsou zatím vratké. Na začátku přípravy je to běžné a Fáze 1 s tím počítá. Jděte pomalu a oranžové lekce druhý den zopakujte.",
  "diag.celkem_nezjisteno": "Dítě stihlo méně než polovinu úloh, výsledek je jen orientační. Pokud to jde, nechte ho diagnostiku dokončit.",
  "diag.celkem_neuplne": "Dítě odevzdalo {odevzdano} z {celkem} úloh. Týdny, ke kterým úlohy nestihlo, jsou označené „Nevíme“.",
  "diag.na_prehled": "Na přehled týdnů",
  "diag.zacit_tyden_1": "Začít týden 1",
  "blok.stitek": "Blok na čas",
  "blok.bezi_nadpis": "Blok na čas běží",
  "blok.pravidlo": "Dítě řeší všechny 4 úlohy samo, vy mlčíte. Smíte říct jen: „Zadej, co máš, a jdi dál.“",
  "blok.cas": "uplynulo z doporučených {cas} min",
  "blok.cas_doporuceno": "doporučený čas",
  "blok.cas_vyprsel": "Doporučený čas uplynul. Řekněte dítěti: „Čas. Dokonči rozdělaný krok.“ Pak klepněte na tlačítko níže.",
  "blok.odevzdano": "Odevzdáno {x} ze {celkem}",
  "blok.konec_app": "Až dítě uvidí „Hotovo, ukaž telefon rodiči“, telefon vás sám přepne na procházení úloh.",
  "blok.konec_papir": "Dítě píše na papír. Až dopíše (nebo po {cas} minutách), klepněte na tlačítko níže. Výsledky z papíru pak opíšete u každé úlohy.",
  "blok.tlacitko": "Čas vypršel, projdeme to spolu",
  "blok.potvrzeni_nadpis": "Projít úlohy už teď?",
  "blok.potvrzeni": "Doporučený čas ještě neuplynul. Na telefonu teď uvidíte řešení a dítě už by nemělo nic měnit.",
  "blok.potvrzeni_ano": "Ano, projdeme to",
  "blok.potvrzeni_zpet": "Ještě ne",
  "blok.auto": "Dítě odevzdalo všechny 4 úlohy. Projděte je spolu od úlohy 1.",
  "blok.pruh": "Po bloku: projděte spolu úlohy 1–4 od začátku. U každé: co nesedělo, otázka, „Hotovo? Zeptejte se“, semafor.",
  "blok.podtitul_po": "Po bloku",
  "blok.postup_1": "Dítě úlohu už vyřešilo. Podívejte se, co zadalo.",
  "blok.postup_1_papir": "Dítě úlohu už vyřešilo na papír. Podívejte se, co napsalo.",
  "blok.postup_2": "Nesedělo to? Přečtěte otázku.",
  "blok.nezaseklo": "Všechno sedělo",
  "blok.zadalo_nadpis": "Dítě zadalo:",
  "blok.zadalo_nic": "Na tuhle úlohu dítě v bloku nedošlo. Projděte ji spolu jako běžnou úlohu.",
  "blok.zadalo_sedi": "sedí",
  "blok.zadalo_nesedi": "nesedí",
  "blok.zadalo_pokus": "na {n}. pokus",
  "blok.zadalo_rysovani": "rýsuje na papíře, porovnáte v kroku 4",
  "blok.zadalo_chybi": "nezadalo",
  "blok.zak_konec": "Blok na čas máš za sebou. Zavolej rodiče, teď spolu projdete všechny 4 úlohy.",
  "f2.rysovani_zak": "Rýsuj na papír. Až to bude hotové, ukaž to rodiči.",
  "f2.rysovani_hotovo": "Hotovo",
  "f2.rysovani_odevzdano": "Hotovo. Rodič teď porovná tvoje rýsování s obrázkem.",
  "f2.rysovani_nadpis": "Rýsování dítěte",
  "f2.rysovani_text": "Položte obrázek vedle papíru dítěte a projděte otázky. Nic neměřte, stačí pohled.",
  "f2.rysovani_otazky": "Zkontrolujte:",
  "f2.rysovani_ceka": "Dítě ještě rýsuje. Porovnejte, až klepne Hotovo nebo vám papír ukáže.",
  "f2.sedi": "Sedí",
  "f2.nesedi": "Nesedí",
  "f2.postup_zak": "Celý postup napiš na papír do rámečku. Sem zadej jen výsledek.",
  "f2.co_vidi_rysovani": "Dítě rýsuje na papír a pak klepne Hotovo.",
  "f2.tisk_postup": "Celý postup",
  "f2.tisk_vysledek": "Výsledek",
  "f2.tisk_rysovani": "Rýsuj sem (měřítko 1 : 1)",
  "f2.tisk_rysovani_stejne_pole": "Rýsuj do stejného pole výše.",
  "f2.tisk_kontrola": "Kontrola tisku: úsečka má měřit 5 cm",
  "f2.tisk_100": "Tiskněte ve skutečné velikosti (100 %), ne „Přizpůsobit stránce“.",
  "sim.start_nadpis": "Simulace přijímaček",
  "sim.start_text": "Doporučené pořadí: 1–8, pak 11–15, nakonec 9–10 a 16. U úlohy nestůj déle než 5 minut, přeskoč ji a vrať se.",
  "sim.start_text_app": "Úlohy jdou popořadě. U úlohy nestůj déle než 5 minut: zadej, co máš, a jdi dál. Každou úlohu odevzdáváš jen jednou.",
  "sim.start_tlacitko": "Začít test",
  "sim.start_2_nadpis": "2. část simulace",
  "sim.start_2_text": "Pokračuješ úlohami 9–16. Čas běží dál od začátku 1. části.",
  "sim.start_2_rozdeleno": "Dnes děláš 2. část. Máš na ni 35 minut.",
  "sim.tempo_40": "Jsi-li ještě v 1. části, přejdi na úlohy 11–15, jsou to rychlé body.",
  "sim.tempo_70": "Čas testu vypršel. U zkoušky byste teď odevzdávali. Udělej na archu čáru, co je pod ní, se nepočítá.",
  "sim.prubeh": "Úloha {pozice} · {cast}. část",
  "sim.ulozeno": "Uloženo.",
  "sim.konec_1_nadpis": "1. část máš za sebou.",
  "sim.konec_1_text": "Pokračuj úlohami 9–16. Čas běží dál.",
  "sim.dalsi_cast": "Pokračovat 2. částí",
  "sim.konec_nadpis": "Test máš za sebou.",
  "sim.konec_sedi": "Tyhle úlohy sedí:",
  "sim.konec_zadna": "Díky za celý test. Rodič s tebou projde, co šlo.",
  "sim.konec_ceka": "Úlohy s postupem a rýsováním ještě zkontroluje rodič.",
  "sim.konec_zitra": "Zítra spolu projdeme 4 úlohy.",
  "sim.papir_nadpis": "Test píšeš na papír",
  "sim.papir_text": "Máš vytištěný testový sešit a záznamový arch. Až odevzdáš, rodič arch zkontroluje a tady uvidíš, které úlohy sedí.",
  "sim.papir_obnovit": "Zkontrolovat znovu",
  "sim.rodic_bezi_nadpis": "Simulace běží",
  "sim.rodic_bezi_text": "Tahák, klíč ani řešení teď nevidíte, aby se k nim nedostalo ani dítě.",
  "sim.rodic_pravidla_nadpis": "Tři pravidla",
  "sim.rodic_pravidlo_1": "Nenapovídejte.",
  "sim.rodic_pravidlo_2": "Nekomentujte. Smíte říct jedinou větu: „Přeskoč ji a vrať se na konci.“",
  "sim.rodic_pravidlo_3": "Přestávka jen na WC, čas běží dál.",
  "sim.rodic_start": "Před startem přečtěte dítěti:",
  "sim.rodic_precist": "Přečtěte dítěti:",
  "sim.rodic_vidi": "Dítě teď vidí na obrazovce:",
  "sim.rodic_odevzdano": "Dítě odevzdalo {x} z {celkem} úloh.",
  "sim.rodic_rozdeleno": "Simulace je rozdělená na dva dny. 2. část má vlastní odpočet 35 minut.",
  "sim.rodic_odevzdalo": "Dítě odevzdalo",
  "sim.rodic_potvrzeni": "Má dítě test odevzdaný? Potom uvidíte klíč a řešení a dítě už by nemělo nic dopisovat.",
  "sim.rodic_potvrzeni_ano": "Ano, odevzdalo",
  "sim.rodic_zpet": "Ještě ne",
  "sim.kontrola_nadpis": "Kontrola",
  "sim.kontrola_uvod_papir": "Jděte po číslech v záznamovém archu. Nic nepočítáte: porovnáte a klepnete. Trvá to asi 15 minut.",
  "sim.kontrola_uvod_app": "Výsledky už aplikace vyhodnotila. Zkontrolujte jen postup a rýsování.",
  "sim.kontrola_cast": "{cast}. část (úlohy {od}–{do})",
  "sim.kontrola_uloha": "Úloha {pozice}",
  "sim.kontrola_spravne": "Správně:",
  "sim.kontrola_uznava": "Uznává se i:",
  "sim.uznava_nezkraceny": "nezkrácený zlomek se stejnou hodnotou",
  "sim.uznava_desetinne": "desetinné číslo",
  "sim.uznava_zlomek": "zlomek",
  "sim.uznava_nepravy": "nepravý zlomek",
  "sim.uznava_poradi_clenu": "jiné pořadí členů se stejnou hodnotou",
  "sim.kontrola_porovnejte": "Sedí to s archem?",
  "sim.kontrola_pismena": "Co dítě zakřížkovalo?",
  "sim.kontrola_nic": "Nic",
  "sim.kontrola_dva": "Dva křížky",
  "sim.kontrola_postup": "Je v rámečku postup, víc než jen výsledek?",
  "sim.kontrola_postup_pozn": "Bez postupu je úloha za 0 bodů, i když výsledek sedí.",
  "sim.ano": "Ano",
  "sim.ne": "Ne",
  "sim.kontrola_typicka_chyba": "Typická chyba",
  "sim.kontrola_zbyva": "Zbývá zkontrolovat: {n}. Co nezkontrolujete, počítá se za 0 bodů.",
  "sim.kontrola_hotovo": "Všechno je zkontrolované.",
  "sim.kontrola_prazdna": "V této části není co kontrolovat, aplikace ji vyhodnotila sama.",
  "sim.kontrola_souhrn": "Zobrazit souhrn",
  "sim.kontrola_ulozeno": "Uloženo",
  "sim.souhrn_nadpis": "Souhrn simulace {cislo}",
  "sim.souhrn_body": "Orientačně {body} z {max} (1. část {b1} z {m1}, 2. část {b2} z {m2}). Jen pro vás.",
  "sim.souhrn_dite": "Dítěti řekněte, co šlo a co zítra zkusíte.",
  "sim.souhrn_orientacni": "Bodování je orientační, u zkoušky se může lišit.",
  "sim.souhrn_rozdeleno": "Simulace byla rozdělená na dva dny (2. část měla vlastní odpočet 35 minut).",
  "sim.souhrn_casti_nadpis": "Podle částí testu",
  "sim.skupina_cisla": "Čísla a zlomky (úlohy 1–2)",
  "sim.skupina_algebra": "Výrazy a rovnice (úlohy 3–4)",
  "sim.skupina_slovni": "Slovní úlohy a geometrie (úlohy 5–8)",
  "sim.skupina_konstrukce": "Konstrukce (úlohy 9–10)",
  "sim.skupina_uzavrene": "Uzavřené úlohy (11–15)",
  "sim.skupina_uloha16": "Úloha 16",
  "sim.skupina_body": "{body} z {max}",
  "sim.souhrn_chyby_nadpis": "Na co dítě nejčastěji naráží",
  "sim.souhrn_chyby_pozice": "V úlohách {pozice}.",
  "sim.souhrn_chyby_pozice_1": "V úloze {pozice}.",
  "sim.souhrn_chyby_prazdne": "Žádná typická chyba se neobjevila.",
  "sim.souhrn_doporuceni_nadpis": "Před zkouškou projděte znovu",
  "sim.souhrn_doporuceni_uloha": "Úloha {pozice}: {lekce}",
  "sim.souhrn_doporuceni_prazdne": "Všechny úlohy sedí. Před zkouškou stačí rozbor a poslední rozcvička.",
  "sim.souhrn_sedi": "Dítě uvidí zeleně úlohy: {pozice}",
  "sim.souhrn_nic_nesedi": "Dítě uvidí poděkování za celý test, žádná úloha zatím nesedí naplno.",
  "sim.lekce_bez_tematu": "{faze}. fáze, {tyden}. týden, {poradi}. lekce",
  "sim.na_prehled": "Na přehled",
  "sim.upravit_kontrolu": "Upravit kontrolu",
  "sim.stitek": "Simulace · {cast}. část",
  "sim.karta_popis_1": "Úlohy 1–8. Pokračuje 2. částí, jeden odpočet 70 minut.",
  "sim.karta_popis_2": "Úlohy 9–16. Navazuje na 1. část.",
  "sim.karta_uloh": "8 úloh",
  "sim.karta_zacit": "Začít simulaci",
  "sim.karta_souhrn": "Souhrn simulace",
  "sim.modal_text": "Doporučujeme papír: vytisknete testový sešit i záznamový arch najednou, jako u zkoušky.",
  "sim.tisk_sesit": "Testový sešit",
  "sim.tisk_prepiste": "V úlohách, kde se nežádá celý postup, přepište do záznamového archu pouze výsledky.",
  "sim.tisk_arch": "Záznamový arch",
  "sim.tisk_krizky": "Křížek z rohu do rohu. Oprava: pole zabarvi a udělej nový křížek. Piš propiskou, rýsuj tužkou a obtáhni.",
  "sim.tisk_vzorce": "Vzorce a tabulka",
  "sim.tisk_mocniny": "Druhé mocniny čísel 11–20",
  "sim.tisk_meritko": "Kontrola tisku: tahle čára má mít přesně 5 cm. Když nemá, tiskněte znovu se 100% měřítkem.",
  "sim.tisk_zacatek": "Začátek",
  "sim.tisk_konec": "Konec",
  "cj.neplatne_klik": "Klikni na slovo ve větě, pak odevzdej.",
  "cj.neplatne_klik_mezery": "Klikni na místo mezi slovy, pak odevzdej.",
  "cj.neplatne_vice": "Vyber aspoň jednu možnost.",
  "cj.neplatne_doplnit": "Doplň písmeno do každé mezery.",
  "cj.neplatne_role": "U každého podtrženého slova vyber, co to je.",
  "cj.neplatne_seradit": "Seřaď všechny položky, pak odevzdej.",
  "cj.neplatne_kratky_text": "Napiš svou odpověď.",
  "cj.neplatne_diktat": "Napiš, co slyšíš, pak odevzdej.",
  "cj.max_vyber": "Můžeš vybrat nejvýš {n}. Nejdřív nějaké zruš.",
  "cj.prehrat": "Přehrát nahrávku",
  "cj.prehrat_vetu": "Přehrát větu {n}",
  "cj.prehrano": "přehráno {n} z {max}",
  "cj.audio_chyba": "Nahrávka se nenačetla. Řekni to rodiči.",
  "cj.dalsi_veta": "Další věta",
  "cj.veta_z": "Věta {n} z {pocet}",
  "cj.posledni_veta": "To byla poslední věta. Až bude všechno napsané, odevzdej.",
  "cj.role_hotovo": "Hotovo",
  "cj.role_vyber": "Vyber, co je slovo „{slovo}“:",
  "cj.zmenit_pismeno": "Změnit písmeno {p}",
  "cj.misto_za": "místo za {n}. slovem",
  "cj.co_vidi_poslech": "Dítě slyší nahrávku, text nevidí.",
  "cj.prepis_nadpis": "Co zazní v nahrávce (nečtěte nahlas)",
  "cj.diktat_text_nadpis": "Text diktátu (nečtěte nahlas)",
  "cj.cist_sam": "Číst sám",
  "cj.cist_sam_pozn": "Nahrávka nejde přehrát. Výjimečně přečtěte věty sami: pomalu, každou dvakrát, bez čárek a teček.",
  "cj.odpoved_nadpis": "Dítě odevzdalo:",
  "cj.chybi": "chybí: {slova}",
  "cj.navic": "navíc: {slova}",
  "cj.nesedi_u": "nesedí u: {slova}",
  "cj.papir_nadpis": "Porovnejte papír dítěte",
  "cj.papir_spravne": "Správně je: {odpoved}",
  "cj.papir_sedi": "Sedí",
  "cj.papir_nesedi": "Nesedí",
  "cj.slovnicek_nadpis": "Co ta slova znamenají",
  "cj.otazka_1": "vlastními slovy",
  "cj.otazka_2": "test na slově",
  "cj.otazka_3": "nápověda",
  "cj.neplatne_klik_min": "Tady je potřeba vybrat aspoň {n}. Pak odevzdej.",
  "cj.neplatne_diktat_dalsi": "Ještě tě čekají další věty. Klepni na „Další věta“.",
  "cj.zastavit": "Zastavit",
  "cj.seradit_napoveda": "Klikej na položky v pořadí, jak jdou za sebou. Dalším klikem číslo zrušíš.",
  "cj.uloha_hotova": "Úloha {n} {z} {celkem} je hotová. Pokračuj další.",
  "cj.co_vidi_diktat": "Dítě pouští nahrávku po větách a píše, co slyší. Text nevidí.",
  "cj.cist_sam_odkaz": "Jen když nahrávka dítěti nejde",
  "cj.papir_prehrat": "Dítě píše na papír: nahrávku mu pusťte z tohoto telefonu.",
  "cj.papir_veta": "Věta {n}",
  "cj.nabidka": "Dítě u každého podtrženého slova vybírá z nabídky:",
  "cj.vybralo": "Vybralo:",
  "cj.doplnilo": "Doplnilo:",
  "cj.napsalo": "Napsalo:",
  "cj.seradilo": "Seřadilo:",
  "cj.nic": "nic",
  "cj.kategorie_rod": "Rod",
  "cj.kategorie_cislo": "Číslo",
  "cj.kategorie_pad": "Pád",
  "cj.kategorie_osoba": "Osoba",
  "cj.kategorie_cas": "Čas",
  "cj.kategorie_zpusob": "Způsob",
  "cj.dite_dalo": "dítě: {hodnota}",
  "cj.mezera_za": "za slovem „{slovo}“",
  "cj.slovo_cislo": "{n}. slovo",
  "cj.znama_chyba": "Známá chyba:",
  "cj.zeptejte_se": "Zeptejte se:",
  "cj.volitelne": "{slova}: může, ale nemusí být vybrané.",
  "cj.uzna_se_i": "Uzná se i: {varianty}",
  "cj.diktat_veta": "Věta",
  "cj.diktat_napsalo": "Dítě napsalo",
  "cj.diktat_ma_byt": "Má být",
  "cj.diktat_bez_chyby": "Diktát je bez chyby.",
  "predmet.prepinac": "Předmět",
  "predmet.matematika": "Matematika",
  "predmet.cestina": "Čeština",
  "predmet.prazdny": "Lekce tohoto předmětu tu budou brzy.",
  "dite.predmety_legenda": "Co bude dítě procvičovat?",
  "dite.predmety_chyba": "Vyberte aspoň jeden předmět.",
  "dite.predmety_tlacitko": "Předměty",
  "dite.predmety_nadpis": "Předměty: {jmeno}",
  "dite.predmety_text": "Když vyberete oba předměty, přehled ukáže u dítěte {jmeno} dvě záložky: Matematika a Čeština.",
  "dite.predmety_ulozit": "Uložit předměty",
  "dite.predmety_ulozeno": "Předměty jsou uložené.",
  "samo.volba_nazev": "Dnes samo",
  "samo.volba_popis_rodic": "Nemáte dnes čas? Dítě pracuje v aplikaci samo, aplikace se ho ptá místo vás.",
  "samo.volba_popis_zak": "Rodič dnes nemá čas. Pracuješ v aplikaci sám nebo sama, aplikace ti poradí.",
  "samo.potvrzeni_zak": "Rodič ví, že dnes pracuji sám nebo sama.",
  "samo.nelze": "Tuhle lekci je potřeba dělat s rodičem, protože rodič kontroluje rýsování. Dnes ji zkuste spolu.",
  "samo.uvod": "Dnes pracuješ sám nebo sama. Když nevíš, jak dál, klikni na „Nevím, jak dál“.",
  "samo.napoveda_tlacitko": "Nevím, jak dál",
  "samo.napoveda_nadpis": "Nápověda {n} ze 3",
  "samo.napovedy_dosly": "Víc nápověd není. Zkus to, jak nejlíp umíš.",
  "samo.chyba_tip": "Častá chyba: {popis}",
  "samo.konec": "Lekce je uložená. Rodič na telefonu uvidí, jak ti to šlo.",
  "samo.rodic_bezi": "Dítě dnes pracuje samo. Ať otevře lekci na počítači nebo tabletu. Až skončí, uvidíte na přehledu, jak to šlo.",
  "samo.stitek": "Bez rodiče",
  "samo.pripominka": "Poslední dvě lekce proběhly bez vás. Příští zkuste spolu, stačí 20 minut.",
  "samo.souhrn": "Lekce proběhla bez vás. Semafor vyhodnotila aplikace podle toho, jak dítě úlohy řešilo.",
  "osma.rytmus": "Každý týden se otevřou 3 lekce z každého předmětu. Nejvýš jedna lekce denně v každém předmětu.",
  "osma.postup": "hotovo {hotovo} {z} {celkem} lekcí",
  "osma.max_lekce_den": "Dnešní lekce z předmětu {predmet} je hotová. Další doporučujeme až zítra.",
  "osma.zamceno": "Zamčeno",
  "osma.zamceno_uzavreno": "Účet je uzavřený.",
  "osma.tema_nadpis": "Téma {tema} · {nazev}",
  "osma.tema_slabe": "Procvičit",
  "osma.tema_nejiste": "Zopakovat",
  "osma.tema_silne": "Jde to",
  "osma.lekce_poradi": "Lekce {n}",
  "osma.lekce_kontrola": "Lekce {n} · kontrola tématu",
  "osma.lekce_naostro": "Lekce {n} · naostro",
  "osma.lekce_kontrola_naostro": "Lekce {n} · kontrola tématu naostro",
  "osma.lekce_b": "Lekce {n} · jiné úlohy",
  "osma.zamceno_kalendar": "Otevře se {datum}. Každý týden 3 lekce.",
  "osma.b_tlacitko": "Zkusit znovu s jinými úlohami",
  "osma.b_popis": "Lekce dopadla červeně. Teď stejná látka s jinými úlohami, ať to sedne.",
  "osma.b_hotovo": "Jiné úlohy: hotovo",
  "osma.pol_stitek": "Pololetní test",
  "osma.pol_nazev": "Pololetní test ({min} min)",
  "osma.pol_text_rodic": "Po 10 týdnech: dítě znovu vyřeší krátké úlohy ze všech témat. Podle výsledku přeskládáme zbytek roku.",
  "osma.pol_text_zak": "Krátké úlohy ze všech témat. Ukážou, co už jde a co ještě potrénovat.",
  "osma.pol_zamceno": "Otevře se {datum}, po 10 týdnech.",
  "osma.pol_vysledek": "Výsledek pololetního testu",
  "osma.doporuceno_podle_pololetniho": "Podle pololetního testu: nejdřív témata, která zatím nejdou.",
  "osma.pocet_uloh_2": "{n} úlohy",
  "osma.pocet_uloh_5": "{n} úloh",
  "osma.doporuceno_nadpis": "Doporučeno teď",
  "osma.doporuceno_podle_testu": "Podle úvodního testu: nejdřív témata, která zatím nejdou. Ta, která jdou, jsou na konci.",
  "osma.doporuceno_bez_testu": "Zatím od základů ke složitějšímu. Po úvodním testu pořadí upravíme podle toho, co dítěti nejde.",
  "osma.doporuceno_osnova": "Od základů ke složitějšímu.",
  "osma.vse_hotovo": "Všechny lekce jsou hotové. Výborně! Kterékoli téma můžete projít znovu.",
  "osma.nic_otevreno": "Další lekce se teprve otevřou.",
  "osma.test_stitek": "Úvodní test",
  "osma.test_nazev": "Úvodní test ({min} min)",
  "osma.test_text_rodic": "Dítě vyřeší asi 20 úloh samo, bez taháku a bez nápověd. Ukáže, která témata mu jdou a kde začít.",
  "osma.test_text_zak": "Asi 20 krátkých úloh. Řeš je sám nebo sama, jak nejlíp umíš. Nikdo to nehodnotí.",
  "osma.test_hotovo_rodic": "Podle výsledku jsou lekce seřazené: nejdřív to, co zatím nejde.",
  "osma.test_hotovo_zak": "Hotovo. Lekce jsou seřazené tak, jak ti to pomůže nejvíc.",
  "osma.test_vysledek": "Výsledek úvodního testu",
  "osma.test_zacit_rodic": "Spustit úvodní test",
  "osma.test_zacit_zak": "Začít test",
  "osma.vysledek_nadpis": "Výsledek úvodního testu",
  "osma.vysledek_celkem": "Odevzdáno {odevzdano} {z} {celkem} úloh.",
  "osma.vysledek_jde": "Co jde",
  "osma.vysledek_nejde": "Co zatím nejde",
  "osma.vysledek_nejiste": "Napůl",
  "osma.vysledek_nic": "Žádné téma.",
  "osma.vysledek_zacit": "Kde začít",
  "osma.vysledek_zacit_text": "Začněte: {tema}. Na přehledu je nahoře pod „Doporučeno teď“.",
  "osma.vysledek_zacit_vse": "Všechna témata jdou. Lekce jděte od začátku, poslouží jako opakování.",
  "osma.vysledek_chyby": "Na co se dívat",
  "osma.vysledek_tlacitko": "Na přehled lekcí",
  "osma.vysledek_nezjisteno": "Dítě odevzdalo méně než polovinu úloh, výsledek je jen orientační.",
  "osma.test_konec_zak": "Hotovo. Díky! Podle testu jsme ti seřadili lekce. Najdeš je na přehledu.",
  "samo.kontrolni_ceka": "Tuhle úlohu zkus nejdřív bez nápovědy. Když napoprvé nevyjde, nápovědy se odemknou.",
  "tema_mat.t1": "Přirozená čísla a dělitelnost",
  "tema_mat.t2": "Desetinná čísla",
  "tema_mat.t3": "Jednotky, obvod a obsah",
  "tema_mat.t4": "Zlomky I",
  "tema_mat.t5": "Zlomky II",
  "tema_mat.t6": "Celá a racionální čísla",
  "tema_mat.t7": "Úhly, trojúhelníky, souměrnost",
  "tema_mat.t8": "Poměr, měřítko, úměrnost",
  "tema_mat.t9": "Procenta a úrok",
  "tema_mat.t10": "Tělesa a slovní úlohy",
  "tema_cj.t1": "Slovní druhy",
  "tema_cj.t2": "Podstatná jména: vzory a koncovky",
  "tema_cj.t3": "Přídavná jména",
  "tema_cj.t4": "Zájmena a číslovky",
  "tema_cj.t5": "Slovesa: způsob, vid, rod",
  "tema_cj.t6": "Vyjmenovaná slova",
  "tema_cj.t7": "Shoda přísudku s podmětem",
  "tema_cj.t8": "Větné členy",
  "tema_cj.t9": "Souvětí a čárka",
  "tema_cj.t10": "Stavba slova a pravopis na švu",
});

/** Názvy kapitol pro {kapitola_nazev}: kód kapitoly (lekce.kapitola) → název malými písmeny. */
export const KAPITOLY = Object.freeze({
  "pocetni-operace": "početní operace",
  "cela-cisla": "celá čísla",
  "zlomky": "zlomky",
  "desetinna-cisla": "desetinná čísla",
  "pomer": "poměr",
  "procenta": "procenta",
  "jednotky": "jednotky",
  "slovni-ulohy": "slovní úlohy",
  "vyrazy": "výrazy",
  "rovnice": "rovnice",
  "geometrie": "geometrie",
  "mix": "smíšené úlohy",
  "simulace": "simulace testu",
  "slovni-druhy": "slovní druhy",
  "podstatna-jmena": "podstatná jména",
  "vzory": "vzory podstatných jmen",
  "slovesa": "slovesa",
  "vyjmenovana-slova": "vyjmenovaná slova",
  "podmet-prisudek": "podmět a přísudek",
  "souveti": "věta a souvětí",
  "pridavna-jmena": "přídavná jména",
  "zajmena-cislovky": "zájmena a číslovky",
  "shoda": "shoda přísudku s podmětem",
  "vetne-cleny": "větné členy",
  "pravopis": "pravopis",
});

/**
 * Vrátí text hlášky s dosazenými proměnnými.
 * Neznámý klíč → vrátí klíč samotný a console.warn. Chybějící proměnná zůstane jako {nazev}.
 * @param {string} klic  např. 'zak.spravne'
 * @param {Object<string, string|number>} [promenne]  např. { n: 2 } pro 'Úloha {n} ze 4 …'
 * @returns {string}
 * @example h('zak.uloha_hotova', { n: 2 }) // 'Úloha 2 ze 4 je hotová. Pokračuj další.'
 */
export function h(klic, promenne = {}) {
  const text = HLASKY[klic];
  if (text === undefined) {
    console.warn(`hlasky.js: neznámý klíč „${klic}"`);
    return klic;
  }
  return text.replace(/\{([a-z0-9_]+)\}/gi, (cely, nazev) =>
    (promenne[nazev] === undefined || promenne[nazev] === null ? cely : String(promenne[nazev])));
}
