// GENEROVÁNO z obsah/manual-rodice.md — needitovat ručně.
// Přegenerování: node nastroje/generuj-hlasky.mjs
//
// Použití:  import { MANUAL_NADPIS, MANUAL_MD } from './manual.js';
//           uzel.append(renderMarkdown(MANUAL_MD));   // obsah.js, po await nacistKnihovny()

/** Nadpis (první řádek „# …" ze zdroje). */
export const MANUAL_NADPIS = "Jak vést lekci";

/** Text v Markdownu (bez úvodního nadpisu). */
export const MANUAL_MD = "::: blok barva=hlavni ikona=pozor\n**Hlavní pravidlo.** ==Vy nepočítáte, nepíšete ani nevysvětlujete. Ptáte se.== Chvalte postup, ne výsledek.\n:::\n\n::: blok barva=zelena ikona=telefon\n**Jak lekce probíhá.** Dítě sedí u počítače, vy vedle s telefonem. Na telefonu vidíte zadání jako dítě a ke každé úloze tahák: otázky, typickou chybu a sbalené řešení. Lekce má 4 úlohy, asi ==20–25 minut==. Odpočet je jen doporučení. Nejvýš jedna lekce denně.\n:::\n\n::: blok barva=zelena ikona=bublina\n**Otázky.** První můžete přečíst vždy. ==Druhou a třetí, až když se dítě zasekne.== U poslední, kontrolní úlohy nečtěte nic, dokud se nezasekne.\n:::\n\n::: blok barva=zelena ikona=hledat\n**Klikání na pořadí.** U některých kroků dítě kliká na znaménka v příkladu v tom pořadí, v jakém by počítalo, a objeví se čísla 1, 2, 3. Nic nepočítá. ==Správné pořadí uvidíte na telefonu.== Když aplikace řekne „nesedí“, neopravujte, přečtěte otázku „když nesedí“.\n:::\n\n::: blok barva=zelena ikona=otocit\n**Otočená role.** Dítě vysvětluje vám: ==„Vysvětli mi, proč…“== Vzorovou odpověď máte v taháku.\n:::\n\n::: blok barva=oranzova ikona=krizek\n**Pozor na pasti.** ==Neptejte se „Chápeš to?“== Odpověď je skoro vždycky „ano“. Když vidíte chybu, neopravujte. Zeptejte se: „Jak to počítáš?“\n:::\n\n::: blok barva=zelena ikona=zarovka\n**Když dítě zírá do zadání:**\n\n1. „Podtrhni všechna čísla i s jednotkami.“\n2. „Označ větu s otazníkem.“\n3. „Vyprávěj mi tu úlohu bez čísel.“\n:::\n\n::: blok barva=semafor ikona=fajfka\n**Semafor.** Po každé úloze klikněte ==podle toho nejtěžšího, co se stalo==. Aplikace ukáže barvu.\n:::\n\n::: blok barva=semafor ikona=hodiny\n**Zítra** se řiďte barvou lekce v souhrnu na konci:\n\n- Zelená: nová lekce.\n- Oranžová: nejdřív 5minutové cvičení z doporučení, pak nová lekce. Je-li cvičení víc, stačí to u poslední úlohy.\n- Červená: dnes skončete a pochvalte snahu. ==Zítra místo nové lekce:== cvičení z doporučení, pak znovu stejná lekce.\n:::\n\n::: blok barva=zelena ikona=sos\n**SOS.** Když se červená opakuje, aplikace nabídne konzultaci s lektorem (30 minut online, 150 Kč). SOS je i v přehledu u kapitoly.\n:::";
