// GENEROVÁNO z obsah/typy-chyb.md — needitovat ručně.
// Přegenerování: node nastroje/generuj-hlasky.mjs
// Ruční kratší popisy pro admin a rodiče mají přednost: web/js/chyby.js (popisChyby).

/** Kód typ_chyby → popis (první věta ze slovníku). */
export const POPISY_TYPU_CHYB = Object.freeze({
  "scital-pred-nasobenim": "Sčítal nebo odčítal dřív, než násobil/dělil (počítal zleva doprava jako při čtení)",
  "poradi-nezalezi": "Myslí si, že na pořadí operací nezáleží, že vyjde vždy totéž",
  "ignoroval-zavorku": "Nespočítal závorku jako první / počítal, jako by tam nebyla",
  "umocnil-jen-cast-zavorky": "Závorku drží jako celek, ale exponent za ní použije jen na poslední číslo v ní",
  "nasobil-pred-mocninou": "Nejdřív násobil a pak umocnil (mocnina má přednost)",
  "mocnina-jako-dvojnasobek": "Druhou mocninu spočítal jako násobení dvěma",
  "mocnina-na-cely-vyraz": "Umocnil víc, než k čemu exponent patří",
  "chybi-zavorka": "Při přepisu slov do výrazu vynechal závorku kolem součtu/rozdílu, který se má spočítat celý",
  "kolikrat-jako-o-kolik": "Místo „kolikrát“ (dělení) počítal „o kolik“ (odčítání); i „dvakrát víc“ čte jako „o dva víc“",
  "o-kolik-jako-kolikrat": "Opak: místo rozdílu počítal podíl",
  "deleni-obracene": "Vydělil v opačném pořadí (dělitel : dělenec), často menší větším",
  "zapomnel-odmocninu": "Vynechal odmocninu, počítal s číslem pod ní",
  "odmocnina-jako-deleni-dvema": "Druhou odmocninu spočítal jako dělení dvěma",
  "odmocnina-jen-z-casti": "Odmocnil jen část výrazu pod odmocninou",
  "odmocnina-po-clenech": "Odmocnil součet/rozdíl po členech",
  "numericka-chyba": "Postup správně, spletl se v počítání (násobilka, přepis)",
  "oznacil-radek-pred-chybou": "V detektivní úloze označil jako chybný řádek před Petrovou chybou (ten je správně)",
  "nasel-az-dusledek": "Poznal, že výsledek nesedí, ale ukázal na řádek za chybou, ne na místo, kde vznikla",
  "minus-krat-minus": "Součin/podíl dvou záporných dal záporný",
  "plus-krat-minus": "Součin kladného a záporného dal kladný",
  "pravidlo-znamenek-pri-scitani": "Použil „mínus a mínus dává plus“ u sčítání",
  "odcitani-zaporneho": "Odečtení záporného čísla počítal jako odečtení kladného",
  "posun-spatnym-smerem": "Na teploměru / číselné ose se posunul opačným směrem, než měl (přičítání doleva, odčítání doprava)",
  "mensi-minus-vetsi": "Od menšího odečetl větší a zapomněl minus (otočil pořadí)",
  "ztratil-znamenko": "Postup správně, ale výsledek napsal bez minus",
  "znamenko-pred-zavorkou": "Minus před závorkou změnil jen u prvního členu (nebo u žádného)",
  "mocnina-zaporneho-bez-zavorky": "U -a^2 umocnil i minus",
  "zaporna-mocnina-v-zavorce": "U (-a)^2 nechal výsledek záporný",
  "porovnani-zapornych": "Záporné číslo s větší absolutní hodnotou považuje za větší",
  "absolutni-hodnota-zaporna": "Absolutní hodnotu záporného čísla nechal zápornou",
  "scital-citatele-i-jmenovatele": "Sečetl/odečetl zvlášť čitatele a zvlášť jmenovatele",
  "neprepocital-citatel": "Našel společného jmenovatele, ale čitatele nerozšířil",
  "nezkratil": "Výsledek správně, ale ne v základním tvaru",
  "upravil-jen-cast-zlomku": "Při krácení nebo rozšiřování vydělil/vynásobil jen čitatel, nebo jen jmenovatel",
  "pricetl-misto-nasobeni": "Při krácení nebo rozšiřování přičetl/odečetl stejné číslo u čitatele i jmenovatele, místo aby násobil/dělil",
  "kratil-ruznym-cislem": "Čitatele a jmenovatele vydělil dvěma různými čísly (obě různá od 1)",
  "kratil-jen-castecne": "Krátil, ale ne největším společným dělitelem, a skončil",
  "kratil-pres-scitani": "Krátil jednotlivé sčítance, ne celý čitatel",
  "cele-cislo-do-citatele-i-jmenovatele": "Celé číslo násobil s čitatelem i jmenovatelem",
  "desetinne-jako-zlomek-spatne": "Chybný převod desetinného čísla na zlomek (nebo naopak)",
  "porovnal-podle-jmenovatele": "Větší jmenovatel = větší zlomek",
  "delil-bez-prevraceni": "Dělil čitatel čitatelem a jmenovatel jmenovatelem, i když to nevychází, nebo násobil bez převrácení",
  "prevratil-prvni": "Při dělení převrátil první zlomek (dělence) místo druhého",
  "prevratil-oba": "Při dělení převrátil oba zlomky (dělence i dělitele)",
  "spolecny-jmenovatel-pri-nasobeni": "Při násobení hledal společného jmenovatele a jmenovatele pak nenásobil",
  "mocnina-jen-citatele": "Umocnil jen čitatel (nebo jen jmenovatel)",
  "slozeny-zlomek-prevratil-horni": "U složeného zlomku převrátil horní zlomek místo dolního",
  "smisene-scital-celou-cast": "Při převodu smíšeného čísla přičetl celou část k čitateli (nenásobil jmenovatelem)",
  "smisene-zmenil-jmenovatel": "Při převodu smíšeného čísla změnil jmenovatel",
  "smisene-nasobil-po-castech": "Smíšená čísla násobil po částech (celé × celé, zlomek × zlomek)",
  "znamenko-zlomku": "Ztratil nebo přesunul minus u zlomku",
  "odmocnil-pred-vypoctem-pod-ni": "Odmocnil dřív, než spočítal celý výraz pod odmocninou: odmocnil jen číslo, které viděl první",
  "dosadil-zaporne-bez-zavorky": "Při dosazení záporného čísla vynechal závorku, mocnina pak „spolkla“ minus",
  "odmocnil-jen-citatel": "U zlomku odmocnil (umocnil) jen horní číslo",
  "mocnina-desetinneho-carka": "U mocniny desetinného čísla špatně umístil čárku",
  "mocnina-po-clenech": "Umocnil každý „kus“ čísla zvlášť (desítky a jednotky) a sečetl",
  "zamenil-mocninu-a-odmocninu": "Místo mocniny spočítal odmocninu, nebo naopak",
  "jednicka-je-prvocislo": "Počítá 1 mezi prvočísla",
  "liche-je-prvocislo": "Liché složené číslo považuje za prvočíslo",
  "rozklad-neuplny": "V rozkladu na prvočísla nechal složené číslo",
  "rozklad-bez-opakovani": "Opakované prvočíslo napsal v rozkladu jen jednou",
  "prehledl-dvojciferny": "Hledá největší dvojciferný dělitel, ale vezme největší součin prvočísel z rozkladu, i když není dvojciferný",
  "prvocislo-misto-delitele": "Místo největšího (dvojciferného) dělitele napsal největší prvočíslo z rozkladu",
  "vynechal-delitel": "Ve výčtu dělitelů chybí 1, číslo samo nebo jeden z dvojice",
  "delitel-nasobek-zamena": "Zaměnil dělitele a násobky",
  "delitelnost-3-podle-posledni-cislice": "O dělitelnosti třemi rozhoduje podle poslední číslice, ne podle ciferného součtu",
  "nsd-nsn-zamena": "Zaměnil největšího společného dělitele a nejmenší společný násobek",
  "znamenko-soucinu-vice-cinitelu": "U součinu tří a více činitelů určil znaménko jen podle prvních dvou",
  "ztratil-znamenko-v-mezikroku": "V mezivýsledku zapomněl minus a počítal dál s kladným číslem",
  "carka-pri-nasobeni": "Při násobení desetinných čísel umístil čárku podle jednoho činitele, nebo čárku vynechal",
  "z-celku-misto-ze-zbytku": "Počítal zlomek z celku, i když zadání říká „ze zbytku“",
  "zamenil-cast-a-zbytek": "Zaměnil odebranou část a zbytek: odpověděl částí místo zbytku (nebo naopak), nebo vzal odebranou část jako základ dalšího zlomku",
  "zlomek-z-cisla-jen-deleni": "Vydělil jmenovatelem a zapomněl vynásobit čitatelem",
  "zlomek-z-cisla-obracene": "Vydělil čitatelem a vynásobil jmenovatelem",
  "secetl-zlomky-ruznych-celku": "Sečetl zlomky, které se vztahují k různým celkům (celek a zbytek)",
  "smisene-zpet-spatne": "Nepravý zlomek převedl zpět na smíšené číslo chybně (zbytek dal do jmenovatele)",
  "smisene-odcitani-po-castech": "Smíšená čísla odečetl po částech a u zlomků odečetl menší od většího",
  "smisene-jako-soucin": "Smíšené číslo bere jako součin celé části a zlomku",
  "o-tretinu-z-vysledku": "„X je o třetinu větší než Y“ počítá třetinu z X místo z Y",
  "jen-cast-bez-celku": "Spočítal jen tu část (třetinu, desetinu…) a zapomněl ji přičíst nebo odečíst",
  "o-tretinu-jako-trikrat": "„O třetinu víc“ počítá jako trojnásobek",
  "o-tretinu-min-jako-tretina": "„O třetinu míň“ počítá jako třetinu z čísla",
  "neslo-zleva": "U operací se stejnou předností nepostupuje zleva",
  "carka-pri-deleni": "Při dělení desetinným číslem neposunul čárku u dělence i dělitele stejně",
  "carka-scitani-pod-sebe": "Při sčítání nebo odčítání zarovnal čísla podle poslední číslice, ne podle čárky",
  "posun-carky-spatnym-smerem": "Při násobení nebo dělení 10, 100, 1 000 posunul čárku opačným směrem",
  "posun-carky-o-spatny-pocet": "Posunul čárku správným směrem, ale o jiný počet míst, než má nul",
  "pripsal-nuly-k-desetinnemu": "Násobení 10 nebo 100 „vyřešil“ připsáním nul za desetinné číslo",
  "o-desetinu-jako-pricist-0-1": "„O desetinu víc“ počítal jako přičtení 0{,}1, ne desetiny z čísla",
  "zlomek-jako-cislice-s-carkou": "Převod zlomek ↔ desetinné číslo „po číslicích“: čitatel a jmenovatel oddělil čárkou, nebo naopak z čísel před a za čárkou udělal zlomek",
  "zlomek-na-desetinne-nepresne": "Zlomek, který desetinně nekončí (třetiny, devítiny…), nahradil zkráceným desetinným číslem a počítal s ním jako s přesnou hodnotou",
  "cast-z-prvniho-misto-predchoziho": "U opakovaného „o desetinu / třetinu / 10 % víc než předchozí“ bere část pořád z prvního čísla",
  "zaokrouhlil-useknutim": "Zaokrouhlil useknutím, nerozhodl podle další číslice",
  "zaokrouhlil-na-spatny-rad": "Zaokrouhlil na jiný řád, než chce zadání (desetiny místo setin apod.)",
  "porovnani-desetinnych-podle-delky": "Desetinné číslo s víc číslicemi za čárkou považuje za větší",
  "pomer-nezkraceny": "Poměr nechal v nezákladním tvaru, i když zadání chce základní",
  "pomer-prevraceny": "Zapsal poměr v opačném pořadí, než určuje věta („A ku B“)",
  "pomer-jako-hodnoty": "Členy poměru bere přímo jako hledaná čísla",
  "deleni-v-pomeru-bez-souctu-dilu": "Při dělení celku v poměru nedělil součtem dílů (dělil počtem členů nebo jedním členem)",
  "deleni-v-pomeru-prohodil": "Části spočítal správně, ale přiřadil je obráceně",
  "prehledl-nasobek-v-zadani": "Přehlédl, že se podmínka týká násobků čísel (dvojnásobky, trojnásobky), a počítal s čísly samotnými",
  "prima-jako-neprima": "U přímé úměry počítal „víc → míň“",
  "neprima-jako-prima": "U nepřímé úměry počítal „víc → víc“",
  "umera-jako-soucet": "Místo násobení nebo dělení přičetl rozdíl („o kolik víc“)",
  "procento-jako-desetina": "1 % počítá jako desetinu (dělí deseti místo stem)",
  "procento-jako-cislo": "Procenta bere jako hotové číslo: odpoví počtem procent, nebo je jako koruny či kusy přičte k celku nebo odečte od celku",
  "spatny-zaklad": "Za základ (100 %) vzal jinou veličinu, než určuje zadání (zbytek, část, novou cenu)",
  "vysledek-bez-prevodu-na-procenta": "Podíl část : celek nechal jako desetinné číslo a nepřevedl na procenta",
  "zdrazeni-sleva-zamena": "Zdražení počítal jako slevu (odečetl), nebo slevu jako zdražení",
  "postupne-procenta-secetl": "Dvě po sobě jdoucí změny o procenta sečetl, jako by obě byly z původní hodnoty",
  "sleva-a-zdrazeni-se-vyrusi": "Myslí si, že zdražení a pak sleva o stejná procenta vrátí původní cenu",
  "obsah-po-desitkach": "U jednotek obsahu převádí po 10 místo po 100 mezi sousedními jednotkami",
  "delka-po-stovkach": "U jednotek délky převádí po 100 (jako u obsahu) místo po 10 mezi sousedními jednotkami",
  "objem-po-desitkach-nebo-stovkach": "U jednotek objemu převádí po 10 nebo po 100 místo po 1 000",
  "litr-zamena": "Zaměnil, čemu se rovná litr (1 l = 1 cm³ nebo 1 m³ místo 1 dm³)",
  "prevod-spatnym-smerem": "Na menší jednotku převádí dělením, na větší násobením (volba směru, ne posun čárky)",
  "zapomnel-prevest-jednotky": "Počítal s čísly v různých jednotkách bez převodu na stejnou jednotku",
  "cas-po-stovkach": "S časem počítá po 100, ne po 60 (přechod přes celou hodinu)",
  "cas-desetinne-jako-minuty": "Desetinnou část hodiny bere jako minuty",
  "jednotka-ve-vysledku-spatne": "Výsledek spočítal dobře, ale uvedl ho v jiné jednotce, než chce zadání",
  "vzorec-v-s-t-zamena": "Ve vztahu dráha = rychlost · čas zaměnil, co se násobí a co dělí",
  "min-a-h-smichane": "Dosadil minuty do rychlosti v km/h (nebo hodiny do km/min) bez převodu",
  "prumerna-rychlost-jako-prumer": "Průměrnou rychlost spočítal jako průměr rychlostí, i když úseky trvaly různě dlouho",
  "setkani-rychlosti-zamena": "U pohybu proti sobě rychlosti odečetl (nebo při dohánění sečetl)",
  "odpovida-na-jinou-otazku": "Spočítal mezivýsledek a odpověděl jím, ne tím, na co se zadání ptá (doba místo času příjezdu, část místo celku)",
  "prehledl-udaj": "Nepoužil jeden z údajů zadání (pauzu, výchozí stav, podmínku)",
  "pocital-se-vsemi-cisly": "Sečetl nebo vynásobil všechna čísla ze zadání bez rozmyslu, co znamenají",
  "soucet-misto-soucinu": "Úlohu s podmínkou stejného součinu řešil jako se stejným součtem: čísla doplnil tak, aby se rovnaly součty",
  "scital-nestejne-cleny": "Sloučil členy s různou proměnnou nebo různou mocninou (i číslo s proměnnou)",
  "x-jako-nula": "Samotné x bere jako 0x nebo ho při slučování vynechá (nevidí u něj koeficient 1)",
  "roznasobil-jen-prvni-clen": "Číslem (nebo výrazem) před závorkou vynásobil jen první člen v závorce",
  "vytknul-neuplne": "Nevytkl největší společný činitel (vytkl jen číslo, jen proměnnou, nebo jen z části členů)",
  "vytknuti-ztratil-jednicku": "Když vytkl celý člen, nechal v závorce místo něj nulu nebo nic",
  "vytknuti-minus-znamenka": "Při vytknutí záporného čísla nezměnil znaménka v závorce",
  "vytknuti-nechal-promennou": "Při dělení členu vytýkaným výrazem vydělil jen číslo a proměnnou v závorce nechal",
  "vytkl-bez-minusu": "Zadání chce vytknout záporný výraz, dítě vytklo kladný (rozklad sedí, ale není to, co úloha chtěla)",
  "upravil-jen-jednu-stranu": "Úpravu (přičtení, násobení, dělení) udělal jen na jedné straně rovnice",
  "prevod-bez-zmeny-znamenka": "Při převodu členu na druhou stranu nezměnil znaménko",
  "delil-jen-cast-strany": "Dělil (násobil) jen jeden člen strany, ne celou stranu",
  "x-odecetl-koeficient": "Z ax = b odečetl koeficient místo dělení",
  "zlomky-vynasobil-jen-zlomek": "Při násobení rovnice jmenovatelem vynásobil jen zlomek, ne ostatní členy",
  "vynechal-x-rovna-nula": "Když vyjde x = 0, myslí si, že rovnice nemá řešení, nebo výsledek nenapíše",
  "zamenil-veliciny-v-rovnici": "Při sestavení rovnice ze slov přiřadil číslo ze zadání k jiné veličině",
  "zapsal-vztah-obracene": "Vztah mezi veličinami ze slov zapsal obráceně: „o 4 mladší“ jako +4, „čtyřikrát víc“ jako dělení, „poloviční“ jako 2r",
  "obvod-obsah-zamena": "Spočítal obvod místo obsahu, nebo naopak",
  "obvod-jen-dve-strany": "Obvod obdélníku počítal jako a + b (zapomněl na dvě další strany)",
  "strana-z-obvodu-bez-poloviny": "Z obvodu obdélníku odečetl známou stranu, ale nevydělil dvěma",
  "trojuhelnik-bez-deleni-dvema": "Obsah trojúhelníku spočítal jako strana krát výška bez dělení dvěma",
  "trojuhelnik-deleni-dvema-dvakrat": "Obsah trojúhelníku dělil dvěma dvakrát: vzal už polovinu základny (nebo výšky) a výsledek ještě vydělil dvěma",
  "vyska-jako-strana": "Za výšku vzal šikmou stranu místo kolmé vzdálenosti",
  "lichobeznik-jedna-zakladna": "U lichoběžníku vzal jen jednu základnu, nebo součet základen nevydělil dvěma",
  "slozeny-utvar-cast-navic": "U složeného útvaru započítal část dvakrát nebo zapomněl odečíst výřez",
  "polomer-prumer-zamena": "Dosadil průměr místo poloměru, nebo naopak",
  "vzorec-kruhu-zamena": "Zaměnil vzorec obvodu a obsahu kruhu (2\\pi r a \\pi r^2)",
  "nasobeni-zavorek-vynechal-soucin": "Při násobení dvou závorek „každý s každým“ některý součin vynechal",
  "dvojclen-na-druhou-bez-soucinu": "(a \\pm b)^2 umocnil po členech, bez dvojnásobného součinu",
  "dvojnasobny-soucin-bez-dvojky": "Prostřední člen napsal jako ab místo 2ab",
  "ctverec-rozdilu-znamenko": "U (a - b)^2 dal špatné znaménko u 2ab nebo u b^2",
  "rozdil-ctvercu-jako-ctverec": "Rozdíl čtverců rozložil jako druhou mocninu dvojčlenu",
  "rozklad-souctu-ctvercu": "Rozložil součet čtverců, jako by to byl rozdíl (součet čtverců rozložit nejde)",
  "vzorec-spatne-a-b": "Ve vzorci špatně určil a a b (vzal koeficient bez odmocnění)",
  "minus-pred-zlomkem-bez-zavorky": "Po vynásobení jmenovatelem nedal čitatel za mínusem do závorky",
  "nasobil-jen-jednim-jmenovatelem": "Rovnici vynásobil jmenovatelem jednoho zlomku, ne společným jmenovatelem",
  "dosadil-vyraz-bez-zavorky": "Dosadil výraz za neznámou bez závorky",
  "dosadil-do-stejne-rovnice": "Vyjádřenou neznámou dosadil zpět do rovnice, ze které ji vyjádřil (vyjde 0 = 0)",
  "vyjadril-bez-deleni-koeficientem": "Při vyjádření neznámé nevydělil koeficientem",
  "dopocital-jen-jednu-neznamou": "Našel jednu neznámou a druhou už nedopočítal",
  "zamenil-x-a-y": "Hodnoty neznámých zapsal prohozené",
  "vyjadril-neznamou-se-zlomkem": "Vyjadřuje neznámou, před kterou je číslo (vyjde zlomek), i když v druhé rovnici stojí neznámá bez čísla a jde vyjádřit bez zlomku",
  "spolecna-prace-secetl-casy": "U společné práce sečetl (nebo zprůměroval) časy místo výkonů",
  "tempo-rychlost-zamena": "Zaměnil tempo (minut na km) a rychlost (km za minutu)",
  "vedlejsi-vrcholovy-zamena": "Vedlejší úhel bere jako shodný, nebo vrcholový jako doplněk do 180°",
  "soucet-uhlu-trojuhelniku-spatne": "Součet úhlů v trojúhelníku bere 360° (nebo 90°)",
  "souhlasne-uhly-doplnil": "U rovnoběžek souhlasný nebo střídavý úhel počítal jako doplněk do 180°",
  "rovnoramenny-uhly-zamena": "U rovnoramenného trojúhelníku dal stejné úhly k hlavnímu vrcholu, ne k základně",
  "prehledl-pravy-uhel": "Přehlédl značku pravého úhlu nebo kolmost (s \\perp t) a úhel dopočítal jinak",
  "doplnil-uhel-do-90": "Úhel dopočítal do 90° místo do 180° (nebo místo toho, aby ho opsal): zaměnil přímý úhel s pravým, i když pravý úhel v obrázku není",
  "trojuhelnikova-nerovnost-porusena": "Připustil třetí stranu stejně dlouhou jako součet dvou zbývajících nebo delší, takže se kratší strany nesetkají",
  "prepona-spatne": "Za přeponu vzal odvěsnu: sčítal čtverce místo odčítání (nebo naopak)",
  "pythagoras-bez-ctvercu": "Sečetl (odečetl) strany bez umocnění",
  "polovina-zakladny-zapomnel": "U rovnoramenného trojúhelníku počítal výšku s celou základnou místo s polovinou",
  "pythagoras-ne-pravouhly": "Použil Pythagorovu větu v trojúhelníku, který není pravoúhlý (nerozdělil ho výškou)",
  "povrch-bez-podstav": "Spočítal jen plášť, nebo jen jednu podstavu",
  "povrch-objem-zamena": "Zaměnil povrch a objem",
  "objem-soucet-rozmeru": "Objem kvádru spočítal jako součet rozměrů",
  "hrana-z-povrchu-bez-deleni": "Z povrchu krychle počítal hranu bez dělení šesti",
  "plast-jen-cast-sten": "Do pláště hranolu započítal jen část bočních stěn (jednu nebo dvě ze čtyř)",
  "pocet-hran-spatne": "Špatně spočítal hrany tělesa (vynechal boční hrany nebo některé počítal dvakrát), a proto špatně určil délku hrany",
  "vyska-meni-i-podstavy": "Při změně výšky hranolu počítal se změnou i u dna a víka (šest stěn místo čtyř bočních)",
  "bod-na-jedne-care": "Hledaný bod umístil jen na jednu z pomocných čar, ne do jejich průsečíku",
  "thaletova-kruznice-spatny-stred": "Thaletovu kružnici vedl se středem v krajním bodu úsečky, ne v jejím středu",
  "kruznice-spatny-stred": "Kružnici pro zadanou délku strany vedl se středem v jiném vrcholu, než ze kterého se délka měří",
  "kolmice-k-jine-primce": "Kolmici (výšku, pravý úhel) vedl k jiné přímce nebo úsečce, než určuje zadání",
  "osa-usecky-mimo-stred": "Osu úsečky vedl kolmo, ale ne středem úsečky",
  "pocet-reseni-spatne": "Našel méně (nebo víc) řešení, než úloha má",
  "uhlopricky-nepulil": "U rovnoběžníku a obdélníku nevyužil, že se úhlopříčky půlí (od středu nanesl celou úhlopříčku)",
  "neoznacil-vrcholy": "Konstrukce je správně, ale vrcholy nejsou označené písmeny",
  "uhlopricky-stejne-zamena": "Zaměnil, kdy jsou úhlopříčky stejně dlouhé: u rovnoběžníku, který není obdélník, dal všechny vrcholy stejně daleko od středu, nebo u obdélníku nevyužil, že jsou všechny vrcholy od středu stejně daleko",
  "strana-misto-uhlopricky": "Zaměnil stranu a úhlopříčku rovnoběžníku nebo obdélníku: protější vrchol hledal na straně místo na úhlopříčce, střed útvaru bral jako střed strany, nebo použil délku strany místo úhlopříčky",
  "zamenil-mnozinu-bodu": "K podmínce ze zadání vybral čáru (množinu bodů), která patří k jiné podmínce: pravý úhel dal na osu úsečky, stejnou vzdálenost od dvou bodů na Thaletovu kružnici, vzdálenost od bodu na rovnoběžku",
  "osa-pres-bod-a-obraz": "Osu souměrnosti vedl přímo přes bod a jeho obraz (spojnici bodů), místo aby vedl kolmici na tuto spojnici jejím středem",
  "prumer-bez-deleni-poctem": "Průměr spočítal jako součet, nebo dělil jiným počtem hodnot",
  "prumer-bez-cetnosti": "Průměr spočítal jen z možných hodnot a nevzal v úvahu, kolik je u každé hodnoty kusů (prostý místo váženého průměru)",
  "rovnost-jako-nerovnost": "Hodnota se rovná hranici z tvrzení, a dítě ji přesto bere jako větší (nebo menší): tvrzení „větší než 70\" označí za pravdivé, i když vyjde přesně 70",
  "prumer-bez-nuly": "Hodnotu 0 nezapočítal do počtu hodnot",
  "cetl-jiny-sloupec": "Odečetl hodnotu z jiného sloupce, řádku nebo kategorie grafu",
  "stupnice-grafu-spatne": "Špatně určil hodnotu dílku stupnice",
  "prirustek-a-hodnota-zamena": "Zaměnil přírůstek (rozdíl) a hodnotu",
  "vysec-stupne-jako-procenta": "U kruhového diagramu vzal stupně výseče jako procenta",
  "rada-stale-pristupek": "Přírůstek určil z prvních dvou obrazců a nepoznal, že se mění",
  "rada-n-krat-prvni": "Počet v n-tém obrazci spočítal jako n krát počet v prvním",
  "rada-posun-o-jednu": "Započítal o jeden přírůstek víc nebo méně (n místo n - 1)",
  "zamenil-poradi-a-pocet": "U otázky „kolikátý obrazec má 100 kusů“ dosadil 100 jako pořadí",
  "zapocital-rohy-dvakrat": "Při počítání dlaždic v rámečku (pásu) kolem čtverce započítal rohové dlaždice dvakrát: vzal čtyřikrát délku strany",
  "vybral-mezivysledek": "U výběru A–E nebo přiřazování zvolil mezivýsledek, který je v nabídce jako past",
  "jina-hodnota-prehledl": "Svůj výsledek v nabídce nenašel, ale nezvolil „jiná hodnota“ (E / F) a vybral nejbližší",
  "jina-hodnota-bez-prepoctu": "Zvolil „jiný\" (E nebo F), i když správný výsledek v nabídce je: svůj chybný výsledek nepřepočítal a nabídku nevzal jako kontrolu",
  "tipnul-bez-vypoctu": "Zvolil možnost nebo ANO/NE odhadem, bez výpočtu",
  "jen-vysledek-bez-postupu": "U úlohy „uveďte celý postup“ napsal jen výsledek (u zkoušky 0 bodů)",
  "prepsal-do-archu-spatne": "V sešitě má správný výsledek, do archu přepsal jiný (přehozené číslice, jiné znaménko)",
  "odpoved-do-spatneho-policka": "Odpověď zapsal nebo zakřížkoval do políčka jiné podúlohy",
  "oprava-bez-preskrtnuti": "Opravu v poli s postupem udělal bez přeškrtnutí: přepsal číslice přes původní zápis, nebo původní nechal a nový napsal vedle",
  "dva-krizky": "Zakřížkoval dvě možnosti, nebo opravu udělal bez zabarvení původního křížku (neplatná odpověď)",
});

/** Detektivní kódy (oddíl B) — ve statistikách zvlášť. */
export const DETEKTIVNI_KODY = Object.freeze(["oznacil-radek-pred-chybou","nasel-az-dusledek"]);
