// GENEROVÁNO z cestina/Obsah/TYPY-CHYB.md — needitovat ručně.
// Přegenerování: node nastroje/generuj-hlasky.mjs (nebo node nastroje/generuj-typy-chyb-cj.mjs)
// Použití přes web/js/chyby.js: popisChyby(kod), otazkaChyby(kod) — i složené kódy diktat-pravopis-<kód>.

/** Kód typ_chyby češtiny → { popis: co dítě udělalo, otazka: otázka pro rodiče „…“ }. */
export const TYPY_CHYB_CJ = Object.freeze({
  "sd-pridavne-za-podstatne": Object.freeze({"popis":"Označí přídavné jméno jako podstatné","otazka":"„Zkus před to říct ten, ta, to. Ten malý… co? Chybí tam něco?“"}),
  "sd-sloveso-za-podstatne": Object.freeze({"popis":"Označí sloveso jako podstatné jméno","otazka":"„Dá se říct ‚to běží‘ jako věc? Nebo to někdo dělá?“"}),
  "sd-vlastnost-neni-podstatne": Object.freeze({"popis":"Neuzná, že radost, odvaha, plavání jsou podstatná jména","otazka":"„Jde říct ‚ta radost‘? Tak co to je?“"}),
  "sd-podstatne-za-sloveso": Object.freeze({"popis":"Označí podstatné jméno slovesné jako sloveso","otazka":"„Jde říct ‚on běh‘? Nebo ‚ten běh‘?“"}),
  "sd-byt-neni-sloveso": Object.freeze({"popis":"Neoznačí slovesa, která „nic nedělají“: je, jsou, byl, má, měl (i v minulém čase)","otazka":"„Jde říct ‚on je‘? Co to slovo ve větě dělá?“"}),
  "sd-minuly-cas-neni-sloveso": Object.freeze({"popis":"Neoznačí tvar minulého času dějového slovesa (šel, vstal, stihl; ne byl, měl — ty jsou `sd-byt-neni-sloveso`)","otazka":"„Jde říct ‚on šel‘? Tak?“"}),
  "sd-infinitiv-neni-sloveso": Object.freeze({"popis":"Infinitiv (běžet, plavat) nevybere jako sloveso, protože test on ___ nefunguje","otazka":"„Jde říct *musím ___*? Říká to slovo, co se dělá?“"}),
  "sd-sloveso-za-pridavne": Object.freeze({"popis":"Označí sloveso jako přídavné jméno","otazka":"„Ptáš se u toho jaký? Nebo co dělá?“"}),
  "sd-pridavne-za-sloveso": Object.freeze({"popis":"Označí přídavné jméno jako sloveso","otazka":"„Jde říct ‚on unavený‘? Nebo ‚jaký? unavený‘?“"}),
  "sd-prislovce-za-pridavne": Object.freeze({"popis":"Příslovce označí jako přídavné jméno","otazka":"„Ptáš se jaký, nebo jak?“"}),
  "sd-prislovce-za-podstatne": Object.freeze({"popis":"Příslovce (jak, kdy, kde) označí jako podstatné jméno","otazka":"„Jde říct ‚ten rychle‘? Říká to jak, ne co.“"}),
  "sd-podstatne-za-pridavne": Object.freeze({"popis":"Podstatné jméno (název) označí jako přídavné jméno","otazka":"„Jde před to říct ten nebo ta? Tak je to název.“"}),
  "prislovce-za-pridavne": Object.freeze({"popis":"Příslovce označí jako přídavné jméno","otazka":"„Jaký, nebo jak?“"}),
  "zajmeno-za-podstatne": Object.freeze({"popis":"Zájmeno označí jako podstatné jméno","otazka":"„Je to jméno věci, nebo to stojí místo jména?“"}),
  "zajmeno-za-pridavne": Object.freeze({"popis":"Přivlastňovací zájmeno (můj, tvůj, náš) určí jako přídavné jméno, protože odpovídá na čí?","otazka":"„Dá se místo toho slova říct něčí jméno? Zkus to.“"}),
  "cislovka-za-pridavne": Object.freeze({"popis":"Číslovku řadovou označí jako přídavné jméno","otazka":"„Ptáš se jaký, nebo kolikátý?“"}),
  "cislovka-jen-cislice": Object.freeze({"popis":"Neuzná číslovku zapsanou slovem","otazka":"„Odpovídá to na kolik?“"}),
  "predlozka-za-prislovce": Object.freeze({"popis":"Předložku označí jako příslovce","otazka":"„Stojí to samo, nebo před nějakým jménem?“"}),
  "prislovce-za-predlozku": Object.freeze({"popis":"Příslovce místa (venku, dole, nahoře) určí jako předložku","otazka":"„Stojí to slovo před nějakým jménem, nebo samo?“"}),
  "spojka-za-castici": Object.freeze({"popis":"Spojku/částici zamění","otazka":"„Spojuje to dvě věci, nebo vyjadřuje přání?“"}),
  "test-zamena": Object.freeze({"popis":"Přiřadí k druhu slova test jiného druhu (ten/ta/to ↔ on ___ ↔ jaký?)","otazka":"„Vyzkoušej ten test nahlas na slově, které znáš. Sedí?“"}),
  "rod-podle-koncovky": Object.freeze({"popis":"Určí rod podle koncovky místo podle ten/ta/to","otazka":"„Řekneš ten táta, nebo ta táta?“"}),
  "rod-z-mnozneho-cisla": Object.freeze({"popis":"Rod slova v množném čísle určí podle ty/ta v množném čísle místo podle jednoho kusu","otazka":"„Řekni to slovo o jednom kusu. Ten, ta, nebo to?“"}),
  "cislo-zamena": Object.freeze({"popis":"Zamění jednotné a množné číslo","otazka":"„Je to jeden, nebo víc?“"}),
  "pad-1-za-4": Object.freeze({"popis":"4. pád určí jako 1. („kdo co“ i u „koho co“)","otazka":"„Zeptej se s pomocným slovem: vidím koho, co? Nebo kdo, co to dělá?“"}),
  "pad-4-za-1": Object.freeze({"popis":"1. pád (kdo, co to dělá) určí jako 4., protože „vidím ___“ zní dobře","otazka":"„Zeptej se slovem z věty: kdo, co to dělá? A dělá to samo, nebo to někdo dělá jemu?“"}),
  "pad-2-za-4": Object.freeze({"popis":"4. pád určí jako 2. (stejný tvar psa)","otazka":"„Které pomocné slovo tam pasuje: bez, nebo vidím?“"}),
  "pad-otazka-bez-predlozky": Object.freeze({"popis":"Ptá se bez pomocného slova, pak nerozliší","otazka":"„Řekni otázku i s pomocným slovem.“"}),
  "pad-2-za-6": Object.freeze({"popis":"6. pád určí jako 2.","otazka":"„Je tam ‚o‘? Tak o kom, o čem.“"}),
  "pad-4-za-7": Object.freeze({"popis":"7. pád určí jako 4.","otazka":"„Je tam ‚s‘? S kým, s čím?“"}),
  "pad-3-za-6": Object.freeze({"popis":"6. pád určí jako 3., protože tvar je stejný jako po k","otazka":"„Jaké krátké slovo je před ním? Řekni otázku i s ním.“"}),
  "pad-6-za-3": Object.freeze({"popis":"3. pád určí jako 6., protože tvar je stejný jako po o","otazka":"„Jaké krátké slovo je před ním? Řekni otázku i s ním.“"}),
  "pad-5-neuzna": Object.freeze({"popis":"Oslovení určí jako 1. pád","otazka":"„Volá ho někdo? Tak který pád to je?“"}),
  "zivotnost-podle-vyznamu": Object.freeze({"popis":"Životnost určí podle toho, zda je věc živá","otazka":"„Nejde o to, jestli žije. Řekni: ten strom – vidím… co?“"}),
  "zivotnost-mimo-muzsky-rod": Object.freeze({"popis":"Určuje životnost u ženského/středního rodu","otazka":"„Jaký je rod? Životnost řešíme jen u ‚ten‘.“"}),
  "vzor-pan-za-muz": Object.freeze({"popis":"Zamění pán/muž","otazka":"„Řekni 2. pád: bez učitel-e nebo učitel-a?“"}),
  "vzor-hrad-za-stroj": Object.freeze({"popis":"Zamění hrad/stroj","otazka":"„Bez pokoj-e nebo pokoj-u?“"}),
  "vzor-podle-1-padu": Object.freeze({"popis":"Vzor určí jen podle 1. pádu","otazka":"„Zkus 2. pád: bez kost-i nebo bez kost-ě?“"}),
  "vzor-ruze-za-pisen": Object.freeze({"popis":"Zamění růže/píseň","otazka":"„Končí to v 1. pádě na -e? Tak?“"}),
  "vzor-pisen-za-kost": Object.freeze({"popis":"Zamění píseň/kost","otazka":"„Bez věc-i nebo věc-e?“"}),
  "vzor-more-za-staveni": Object.freeze({"popis":"Zamění moře/stavení","otazka":"„Bez náměstí, nebo bez náměstě?“"}),
  "vzor-muz-za-soudce": Object.freeze({"popis":"Zamění vzor muž a soudce (přehlédne, že slovo v 1. pádě končí na -e)","otazka":"„Řekni to slovo s *ten*. Jakým písmenem končí? A jak končí vzor?“"}),
  "vzor-pan-za-predseda": Object.freeze({"popis":"Zamění vzor pán a předseda (životné slovo na -a dá k pánovi)","otazka":"„Řekni *ten ___*. Končí slovo souhláskou, nebo samohláskou?“"}),
  "vzor-more-za-kure": Object.freeze({"popis":"Zamění vzor moře a kuře (nevyzkouší 2. pád)","otazka":"„Řekni *bez ___*. Přibude na konci kousek slova, nebo zůstane stejné?“"}),
  "koncovka-podst-i-za-y": Object.freeze({"popis":"V koncovce podst. jména napíše i místo y","otazka":"„Který vzor? Dosaď ho: mezi hrad-?“"}),
  "koncovka-podst-y-za-i": Object.freeze({"popis":"Napíše y místo i","otazka":"„Který vzor? Dosaď ho.“"}),
  "vzor-neurcen": Object.freeze({"popis":"Doplní písmeno bez určení vzoru („podle citu“)","otazka":"„Podle čeho jsi to vybral? Který vzor?“"}),
  "pridavne-tvrde-za-mekke": Object.freeze({"popis":"Měkké (jarní) určí jako tvrdé nebo naopak","otazka":"„Řekni to s ten, ta, to. Mění se konec?“"}),
  "privlastnovaci-neuzna": Object.freeze({"popis":"Tátovo, sestřin neoznačí jako přídavné jméno","otazka":"„Ptáš se čí? Tak co to je?“"}),
  "pridavne-privlastnovaci-za-tvrde": Object.freeze({"popis":"Přivlastňovací přídavné jméno určí jako tvrdé, protože se mu s ten, ta, to mění konec","otazka":"„Na jakou otázku to slovo odpovídá: *jaký?*, nebo *čí?*“"}),
  "koncovka-prid-y-za-i": Object.freeze({"popis":"Napíše „malý psi“","otazka":"„Jde říct TI malí? Nebo TEN malý?“"}),
  "koncovka-prid-i-za-y": Object.freeze({"popis":"Napíše „malí pes“","otazka":"„Ten, nebo ti?“"}),
  "pridavne-shoda-s-jinym-jmenem": Object.freeze({"popis":"Koncovku přizpůsobí jinému slovu ve větě","otazka":"„Ke kterému slovu to přídavné jméno patří?“"}),
  "osoba-podle-podmetu-slova": Object.freeze({"popis":"Osobu určí podle toho, o kom se mluví, ne podle tvaru","otazka":"„Dosaď: já píše, nebo on píše?“"}),
  "infinitiv-urci-osobu": Object.freeze({"popis":"U infinitivu určí osobu","otazka":"„Jde říct on psát? Má to vůbec osobu?“"}),
  "cas-budouci-za-pritomny": Object.freeze({"popis":"Budoucí tvar bez bude (napíšu, přijedeš, pojedeme) určí jako přítomný","otazka":"„Děje se to teď, nebo až potom?“"}),
  "cas-minuly-neuzna-bez-jsem": Object.freeze({"popis":"Tvar psal bez „jsem“ neurčí jako minulý","otazka":"„Stalo se to už? Končí na -l?“"}),
  "zpusob-rozkaz-za-oznam": Object.freeze({"popis":"Rozkaz určí jako oznamovací","otazka":"„Někdo to říká, nebo přikazuje?“"}),
  "zpusob-podmin-za-oznam": Object.freeze({"popis":"Tvar s bych, bys, by, bychom, byste určí jako oznamovací (přehlédne by)","otazka":"„Je u toho slovesa ještě nějaké malé slovo? Co říká?“"}),
  "zpusob-byl-za-podminovaci": Object.freeze({"popis":"Tvar minulého času byl, byla, bylo, byli považuje za podmiňovací, protože začíná na by","otazka":"„Řekni to slovo celé. Je to samostatné *by*, nebo jiné slovo? Kdy se to stalo?“"}),
  "bysme-za-bychom": Object.freeze({"popis":"Napíše/vybere bysme","otazka":"„Jak se to řekne správně u ‚my‘? My… bychom.“"}),
  "by-jsme-za-bychom": Object.freeze({"popis":"Napíše by jsme","otazka":"„Je to jedno slovo, nebo dvě?“"}),
  "by-jsem-za-bych": Object.freeze({"popis":"Napíše nebo vybere by jsem, by jsi, by jste místo jednoslovného tvaru","otazka":"„Je to jedno slovo, nebo dvě? Řekni celou řadu od *já* po *oni*.“"}),
  "by-i-za-y": Object.freeze({"popis":"V bych, bys, by, bychom, byste napíše i (bich, bis, bi)","otazka":"„Jak píšeš slovo *byl*? Ze stejného slova je i tohle.“"}),
  "vs-b-i-za-y": Object.freeze({"popis":"Po B napíše i místo y („bidlit“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-b-y-za-i": Object.freeze({"popis":"Po B napíše y místo i („byčí“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-l-i-za-y": Object.freeze({"popis":"Po L napíše i místo y („mlín“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-l-y-za-i": Object.freeze({"popis":"Po L napíše y místo i („lyst“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-m-i-za-y": Object.freeze({"popis":"Po M napíše i místo y („mislet“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-m-y-za-i": Object.freeze({"popis":"Po M napíše y místo i („mýsa“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-p-i-za-y": Object.freeze({"popis":"Po P napíše i místo y („pitel“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-p-y-za-i": Object.freeze({"popis":"Po P napíše y místo i („pysmo“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-s-i-za-y": Object.freeze({"popis":"Po S napíše i místo y („sichravý“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-s-y-za-i": Object.freeze({"popis":"Po S napíše y místo i („syla“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-v-i-za-y": Object.freeze({"popis":"Po V napíše i místo y („visoký“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-v-y-za-i": Object.freeze({"popis":"Po V napíše y místo i („vydět“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-z-i-za-y": Object.freeze({"popis":"Po Z napíše i místo y („jazik“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-z-y-za-i": Object.freeze({"popis":"Po Z napíše y místo i („zyma“)","otazka":"„Je to vyjmenované slovo, nebo příbuzné s nějakým? S kterým?“"}),
  "vs-pribuzne-neuzna": Object.freeze({"popis":"Nepozná příbuzné slovo","otazka":"„Od kterého slova je to odvozené?“"}),
  "vs-predpona-vy-i": Object.freeze({"popis":"V předponě vy- napíše i","otazka":"„Je tam vy- jako předpona? Vy-běhnout, vy-jít?“"}),
  "vs-dvojice-vyznam": Object.freeze({"popis":"Zamění dvojici podle významu","otazka":"„Co to slovo ve větě znamená? Které z dvojice to je?“"}),
  "vs-rada-poradi": Object.freeze({"popis":"Seřadí vyjmenovaná slova v jiném pořadí, než jdou v řadě","otazka":"„Řekni celou řadu nahlas od začátku, pomalu. Sedí to pořadí s tím, co máš na obrazovce?“"}),
  "podmet-za-predmet": Object.freeze({"popis":"Za podmět označí předmět (4. pád)","otazka":"„Kdo to dělá? Kdo vidí?“"}),
  "podmet-prvni-slovo": Object.freeze({"popis":"Za podmět vezme první slovo věty","otazka":"„Zeptej se u slovesa: kdo, co přišel?“"}),
  "prisudek-neni-sloveso": Object.freeze({"popis":"Za přísudek označí jiné slovo","otazka":"„Které slovo říká, co se děje?“"}),
  "podmet-prisudek-zamena": Object.freeze({"popis":"Za podmět označí přísudek (sloveso), nebo naopak","otazka":"„Které slovo říká, co se děje? A které říká, kdo to dělá?“"}),
  "shoda-y-za-i": Object.freeze({"popis":"Napíše „chlapci běželY“","otazka":"„Kdo běžel? Řekneš TI chlapci? Tak?“"}),
  "shoda-i-za-y": Object.freeze({"popis":"Napíše „stromy rostlI“ / „ženy šlI“","otazka":"„Ti stromy, nebo ty stromy?“"}),
  "shoda-y-za-a": Object.freeze({"popis":"U podmětu středního rodu v množném čísle napíše y místo a","otazka":"„Ta kuřata → jaké písmeno?“"}),
  "shoda-podle-blizkeho-slova": Object.freeze({"popis":"Shodu udělá podle slova vedle slovesa, ne podle podmětu","otazka":"„Kdo leží? Míče, nebo kluci?“"}),
  "shoda-nekolikanasobny-y": Object.freeze({"popis":"U více podmětů s mužským životným napíše y","otazka":"„Je mezi nimi někdo, komu řekneš TEN a je živý?“"}),
  "shoda-nevyjadreny-neurcen": Object.freeze({"popis":"U chybějícího podmětu neví, podle čeho","otazka":"„Kdo přišel? Dosaď si ho z předchozí věty.“"}),
  "shoda-deti-i": Object.freeze({"popis":"Napíše „děti si hrálI“","otazka":"„Ty děti, nebo ti děti?“"}),
  "shoda-rodice-lide-y": Object.freeze({"popis":"U podmětu rodiče, lidé napíše -y („ty rodiče“)","otazka":"„Řekni nahlas: *ti rodiče*, nebo *ty rodiče*? Jak to zní ve škole?“"}),
  "souveti-pocet-podle-spojek": Object.freeze({"popis":"Počítá věty podle spojek/čárek, ne podle přísudků","otazka":"„Kolik je tam sloves, která něco dělají?“"}),
  "souveti-infinitiv-jako-veta": Object.freeze({"popis":"Infinitiv počítá jako samostatnou větu","otazka":"„Má ‚jít‘ svou osobu? Nebo patří k ‚chci‘?“"}),
  "carka-chybi-ze": Object.freeze({"popis":"Chybí čárka před že","otazka":"„Kolik je tam vět? Kde jedna končí a druhá začíná?“"}),
  "carka-chybi-ktery": Object.freeze({"popis":"Chybí čárka před který","otazka":"„Kolik je tam vět? Kde jedna končí a druhá začíná?“"}),
  "carka-chybi-pred-spojkou": Object.freeze({"popis":"Nenapíše čárku před jinou spojkou než že a který (protože, aby, když, ale)","otazka":"„Kolik je tam vět? Kde jedna končí a druhá začíná?“"}),
  "carka-chybi-za-uvodni-vetou": Object.freeze({"popis":"Nenapíše čárku za větou na začátku souvětí (Když…)","otazka":"„Najdi obě slovesa. Kde končí první věta a začíná druhá?“"}),
  "carka-navic-a": Object.freeze({"popis":"Čárka před a při pouhém spojení","otazka":"„Spojuje to ‚a‘ jen dvě věci za sebou?“"}),
  "carka-pred-a-vzdy": Object.freeze({"popis":"Dítě tvrdí, že před a se čárka nepíše nikdy / píše vždy","otazka":"„Platí to vždy? Co říká pravidlo v taháku?“"}),
  "me-mne-zamena": Object.freeze({"popis":"Napíše „dej to mě“ / „vidí mně“","otazka":"„Dosaď tě nebo tobě. Které pasuje?“"}),
  "s-z-predlozka-zamena": Object.freeze({"popis":"Napíše „jdu s domu“ / „z mámou“","otazka":"„S kým, s čím – nebo z koho, z čeho?“"}),
  "predlozka-se-za-zajmeno": Object.freeze({"popis":"Předložku se (se mnou) určí jako zájmeno se u slovesa","otazka":"„Stojí to slovo před někým (s kým?), nebo patří ke slovesu?“"}),
  "detektiv-jine-slovo": Object.freeze({"popis":"Dítě klikne na správné slovo (které chybu nemá)","otazka":"„Petr měl chybu jen v jednom slově. Zkontroluj to označené znovu podle testu.“"}),
  "detektiv-oprava-jine-chyby": Object.freeze({"popis":"Najde správné slovo, ale zvolí špatný důvod/opravu","otazka":"„Slovo máš. Proč je špatně? Vezmi test z taháku.“"}),
  "diktat-vynechane-slovo": Object.freeze({"popis":"Ve zápisu chybí slovo","otazka":"„Přehraj si větu ještě jednou a počítej slova.“"}),
  "diktat-jine-slovo": Object.freeze({"popis":"Dítě napsalo jiné slovo (přeslech)","otazka":"„Poslechni si větu znovu, jen to jedno slovo.“"}),
  "diktat-slovo-navic": Object.freeze({"popis":"V zápisu je slovo navíc, které v diktátu nezaznělo","otazka":"„Přehraj si větu ještě jednou a počítej slova. Kolik jich slyšíš?“"}),
  "ohebnost-stupnovani": Object.freeze({"popis":"Příslovce označí jako ohebné, protože jde stupňovat","otazka":"„Zkus to slovo říct v jiném pádě nebo s *já, ty, on*. Jde to? Je stupňování totéž?“"}),
  "sd-podstatne-za-prislovce": Object.freeze({"popis":"Podstatné jméno, které zná jako „kdy?“, určí jako příslovce","otazka":"„Je před tím slovem *ten*? Jde na něj ukázat jako na věc?“"}),
  "vzor-zena-za-predseda": Object.freeze({"popis":"Mužské jméno na -a dá ke vzoru žena","otazka":"„Řekni před to slovo *ten*, nebo *ta*. Který vzor má stejný rod?“"}),
  "stupnovani-nepravidelne-pravidelne": Object.freeze({"popis":"Nepravidelné stupňování utvoří pravidelně","otazka":"„Řekni to ve větě: Tenhle dort je ještě ___ než ten druhý. Jak to zní?“"}),
  "stupnovani-zamena": Object.freeze({"popis":"Zamění 2. a 3. stupeň","otazka":"„Srovnáváš dvě věci, nebo vybíráš tu úplně ze všech?“"}),
  "privlastnovaci-i-za-y": Object.freeze({"popis":"V přivlastňovacím přídavném jménu napíše -ovi tam, kde patří -ovy","otazka":"„Řekni před podstatné jméno *ti*, nebo *ty*. Co se k němu hodí?“"}),
  "privlastnovaci-y-za-i": Object.freeze({"popis":"Napíše -ovy tam, kde patří -ovi","otazka":"„Řekni před podstatné jméno *ti*, nebo *ty*. Co se k němu hodí?“"}),
  "zajmeno-druh-zamena": Object.freeze({"popis":"Zamění druh zájmena","otazka":"„Co to slovo ve větě dělá: ptá se, ukazuje, něco popírá, nebo připojuje další větu?“"}),
  "jenz-rod-zamena": Object.freeze({"popis":"Použije jenž/jež v jiném rodě","otazka":"„Ke kterému slovu se to zájmeno vztahuje? Řekni před něj *ten, ta*, nebo *to*.“"}),
  "zajmeno-ji-delka": Object.freeze({"popis":"Napíše jí ve 4. p. nebo ji ve 3. a 7. p.","otazka":"„Dosaď místo toho slova *Lucku*, nebo *Lucce*. Které se hodí?“"}),
  "zajmeno-jeho-po-predlozce": Object.freeze({"popis":"Po předložce použije jeho, jemu místo něho, němu (u osobního zájmena)","otazka":"„Stojí před zájmenem krátké slovo jako *pro, k, bez*? Řekni to nahlas i s ním.“"}),
  "cislovka-druh-zamena": Object.freeze({"popis":"Zamění druh číslovky","otazka":"„Na co se ptáš: kolik? kolikátý? kolikery? kolikrát?“"}),
  "cislovka-hovorovy-tvar": Object.freeze({"popis":"Vybere/napíše hovorový tvar dvouma, třema, čtyřma (ne u částí těla)","otazka":"„Jak to napíšeš v písemce? Řekni řadu: se dvěma, se třemi, se …“"}),
  "cislovka-pad-zamena": Object.freeze({"popis":"Zamění tvar 2./6. a 3./7. pádu","otazka":"„Na jakou otázku to odpovídá: s kým? bez koho? o kom? ke komu?“"}),
  "vid-zamena": Object.freeze({"popis":"Určí dokonavé sloveso jako nedokonavé nebo naopak","otazka":"„Dej to sloveso do neurčitého tvaru a zkus: *budu ___*. Jde to?“"}),
  "bude-s-dokonavym": Object.freeze({"popis":"Utvoří budoucí čas dokonavého slovesa s budu","otazka":"„Jde říct *budu přečíst*? Jak řekneš, že to zítra dokončíš?“"}),
  "rod-trpny-za-byt": Object.freeze({"popis":"Tvar být bez příčestí (byl doma) určí jako rod trpný","otazka":"„Děje se tu s Luckou něco, nebo jen říká, kde je? Je za *byla* tvar na *-n, -t*?“"}),
  "rod-trpny-neuzna": Object.freeze({"popis":"Rod trpný určí jako činný","otazka":"„Dělá to ten, o kom se mluví, nebo se to děje s ním?“"}),
  "prisudek-slovesny-za-jmenny": Object.freeze({"popis":"Slovesný přísudek se slovesem být (byla doma) určí jako jmenný","otazka":"„Říká to, jaká nebo kdo Klára je, nebo kde je?“"}),
  "prisudek-jmenny-za-slovesny": Object.freeze({"popis":"Jmenný přísudek se sponou určí jako slovesný","otazka":"„Je za *je* slovo, které říká, kdo nebo jaký podmět je?“"}),
  "prisudek-jmenny-jen-spona": Object.freeze({"popis":"U jmenného přísudku označí jen je, byl","otazka":"„Co se o sousedovi říká? Stačí samo *je*?“"}),
  "predmet-za-pu": Object.freeze({"popis":"Předmět určí jako příslovečné určení","otazka":"„Zeptej se od slovesa. Hodí se otázka *kde? kdy? jak? proč?*, nebo pádová otázka?“"}),
  "pu-za-predmet": Object.freeze({"popis":"Příslovečné určení určí jako předmět","otazka":"„Zeptej se od slovesa. Hodí se otázka *kde? kdy? jak? proč?*, nebo pádová otázka?“"}),
  "pu-druh-zamena": Object.freeze({"popis":"Zamění druh příslovečného určení","otazka":"„Jakou otázkou se na to zeptáš: kde, kdy, jak, nebo proč?“"}),
  "privlastek-shoda-zamena": Object.freeze({"popis":"Zamění přívlastek shodný a neshodný","otazka":"„Změň tvar jména: bez domu … Mění se ten přívlastek s ním?“"}),
  "privlastek-neshodny-za-pu": Object.freeze({"popis":"Přívlastek neshodný určí jako příslovečné určení","otazka":"„Ke kterému slovu to patří: ke jménu, nebo ke slovesu? Zeptej se od něj.“"}),
  "pu-za-privlastek": Object.freeze({"popis":"Příslovečné určení určí jako přívlastek","otazka":"„Ke kterému slovu to patří: ke jménu, nebo ke slovesu? Zeptej se od něj.“"}),
  "veta-hlavni-za-vedlejsi": Object.freeze({"popis":"Zamění větu hlavní a vedlejší (řídí se pořadím)","otazka":"„Kterou z těch vět řekneš samotnou? Kterou začíná slovo jako *že, když, který*?“"}),
  "carka-vlozena-chybi-druha": Object.freeze({"popis":"U vložené vedlejší věty chybí čárka na jejím konci","otazka":"„Kde vedlejší věta končí? Najdi její sloveso a podívej se, co je za ní.“"}),
  "carka-vycet-chybi": Object.freeze({"popis":"Ve výčtu bez spojky chybí čárka","otazka":"„Kolik věcí je vyjmenováno? Co je mezi nimi?“"}),
  "carka-chybi-pred-ale": Object.freeze({"popis":"Ve větě jednoduché chybí čárka před ale","otazka":"„Spojuje *ale* dvě věci, které jdou spolu, nebo staví jednu proti druhé?“"}),
  "carka-navic-pred-i-ani-nebo": Object.freeze({"popis":"Napíše čárku před i, ani, nebo ve slučovacím spojení","otazka":"„Spojuje to slovo jen dvě věci za sebou, podobně jako *a*?“"}),
  "carka-osloveni-chybi": Object.freeze({"popis":"Neoddělí oslovení","otazka":"„Na koho se ve větě volá? Kde to volání končí?“"}),
  "stavba-hranice-zamena": Object.freeze({"popis":"Určí hranici předpony a kořene jinde","otazka":"„Najdi slovo bez předpony, ze kterého je to utvořené. Kde začíná?“"}),
  "stavba-cast-zamena": Object.freeze({"popis":"Zamění části slova (předponu, kořen, příponu, koncovku)","otazka":"„Která část zůstane stejná ve všech příbuzných slovech?“"}),
  "zdvojene-chybi": Object.freeze({"popis":"Na švu napíše jen jednu ze dvou stejných souhlásek","otazka":"„Rozlož slovo na části. Končí jedna část stejným písmenem, jakým začíná další?“"}),
  "zdvojene-navic": Object.freeze({"popis":"Napíše dvě souhlásky tam, kde je jedna","otazka":"„Ze kterého slova je utvořené? Kolik *n* má jeho základ a kolik přípona?“"}),
  "u-krouzek-za-carku": Object.freeze({"popis":"Napíše ů na začátku kořene po předponě","otazka":"„Rozlož slovo. Jak začíná slovo bez předpony?“"}),
  "u-carka-za-krouzek": Object.freeze({"popis":"Napíše ú uvnitř domácího slova","otazka":"„Stojí to *ú* na začátku slova, nebo hned za předponou?“"}),
  "s-z-predpona-zamena": Object.freeze({"popis":"Zamění předponu s- a z-","otazka":"„Co se tím dějem stane: jde něco dolů nebo dohromady, nebo se něco změní?“"}),
  "skupina-e-za-je": Object.freeze({"popis":"Napíše bě, vě na švu ob-, v- + je-","otazka":"„Rozlož slovo: je na začátku předpona *ob-* nebo *v-*? Jak začíná zbytek?“"}),
  "skupina-je-za-e": Object.freeze({"popis":"Napíše bje, vje bez předpony","otazka":"„Rozlož slovo: je na začátku předpona *ob-* nebo *v-*? Jak začíná zbytek?“"}),
  "skupina-me-za-mne": Object.freeze({"popis":"Napíše mě tam, kde patří mně","otazka":"„Najdi příbuzné slovo. Je v něm *mn* nebo *men*?“"}),
  "skupina-mne-za-me": Object.freeze({"popis":"Napíše mně tam, kde patří mě","otazka":"„Najdi příbuzné slovo. Je v něm *mn* nebo *men*?“"}),
});
